### ISSUE TITLE
EnderIO painted glowstone texture issue

### ISSUE THREAD

**Issue by fedoaa** [Chisel-Team/ConnectedTexturesMod#10]
EnderIO painted glowstone texture is no longer connected after updating FTB Beyond to 1.10.0

FTB Beyond 1.9.0 (Chisel 0.0.10.22):
[http://i.imgur.com/TArnB67.png](http://i.imgur.com/TArnB67.png)

FTB Beyond 1.10.0 (Chisel 0.0.11.25 + ConnectedTexturesMod 0.1.1.16):
[http://i.imgur.com/y8WgG8B.png](http://i.imgur.com/y8WgG8B.png)

**Comment by tterrag1098** [comment]
Blame FTB, EIO has had this fixed for a while, check the changelog here: https://minecraft.curseforge.com/projects/ender-io/files/2435810
