### ISSUE TITLE
Lost Cactus/Sugar Cane textures on Sponge

### ISSUE THREAD

**Issue by 0Lynk** [Chisel-Team/ConnectedTexturesMod#100]
![](https://user-images.githubusercontent.com/40400852/59565502-13484980-9087-11e9-8720-28be5b028b15.png)

modlist:
![modlist](https://user-images.githubusercontent.com/40400852/59565554-cb75f200-9087-11e9-8794-e66496b3fc6f.PNG)

[logs of server](https://pastebin.com/gnWV5qpi)
[logs of client](https://pastebin.com/YgkEjEdx)

**Comment by tterrag1098** [comment]
And this issue goes away if you remove CTM?
