### ISSUE TITLE
DELETED. I SMOKED SOMETHING....

### ISSUE THREAD

**Issue by Cosmoros-git** [Chisel-Team/ConnectedTexturesMod#101]
[I am bad person.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/3316214/I.am.bad.person.txt)

**Comment by tterrag1098** [comment]
CTM doesn't even exist for 1.7.10

**Comment by Cosmoros-git** [comment]
WHAT MAGIC WAS THAT?! I WAS SURE I DOWNLOADED 1.7.10 VERSION 0_0. WHAT DID I SMOKED?
