### ISSUE TITLE
CTM Models don't render when used as submodels in Forge Blockstate

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/ConnectedTexturesMod#105]
Test pack: [ctm_blockstate_submodel.zip](https://github.com/Chisel-Team/ConnectedTexturesMod/files/3451336/ctm_blockstate_submodel.zip)

Expectation: Where you see Cobble Posts, they should be incased in glass itself. However the glass doesn't render because Forge isn't rendering the submodel.

Also provided: Working glass models, not used as submodels.

![2019-07-31_03 56 10](https://user-images.githubusercontent.com/5010174/62206659-28332080-b347-11e9-892f-1f9d69437732.png)

**Comment by tterrag1098** [comment]
The cause is that the layer checks don't pass through the multipart model. There's not much I can do about this, without significantly slowing down layer checks. The fix is to set the block layer properly in code.
