### ISSUE TITLE
Glass Pane in corners have not connected texture

### ISSUE THREAD

**Issue by VincentLongiug** [Chisel-Team/ConnectedTexturesMod#107]
On a large window, if a Pane is linked to another one which is on an other axis than the window, its texture is no longer connected to any other Pane : 

![2019-08-15_16 17 09](https://user-images.githubusercontent.com/52882424/63100902-4d937180-bf78-11e9-8574-2f20e1d3cb95.png)
Note : I modified the CTP so the Panes have no longer the issue referenced in #30 and [here](https://github.com/Chisel-Team/ConnectedTexturesPack/issues/3), but please don't tell me that's why I have this issue : it was already there before and the border is on the non-corner Panes

Minecraft : 1.12.2
CTM : 0.3.3.22
CTP : 1.2 for MC 1.12 (customized)

**Comment by tterrag1098** [comment]
This is intended behavior when connect_inside is false (the default)

**Comment by VincentLongiug** [comment]
Oh... my bad... ~~Thanks, I close this issue then~~
I tried to turn it true but it doesn't change anything on the moment. I guessed it needed a restart.
So did I, but it caused this config to turn back to false, and I'm stuck with the disconnexion.
The other config (disableCTM) has the same problem.
I modified configs of other mods and they didn't do this

**Comment by tterrag1098** [comment]
Not the config, it's a flag in the texture data. https://github.com/Chisel-Team/ConnectedTexturesMod/wiki/Extra-Data#ignoring-states-and-obscured-faces

**Comment by VincentLongiug** [comment]
Got it, thanks !
I still think the config should be able do it for us, but at least for now, I can patch it by myself.
*I'll also try to get rid of the horizontal stripes between the Panes while I'm on it.*
