### ISSUE TITLE
Several missing texture glitches (possible mod incompatibility?)

### ISSUE THREAD

**Issue by DoomRater** [Chisel-Team/ConnectedTexturesMod#108]
Breaking a 3x3 section of limestone with an infused destructive pickaxe results in the surrounding 8 limestone blocks breaking with the "missing textures" particles.  I haven't restested with an Immersive Engineering Mining Drill.

Placing a secret trapdoor next to a limestone block will cause the trapdoor to correctly grab the correct limestone texture, but the surrounding sides of the trapdoor will be x-rayed blocks.  Screenshots: https://imgur.com/a/IS18zJi

Forge 14.23.5.2838
Chisel MC1.12.2-0.2.1.35
CTM ME1.12.2-0.3.3.22
Secret Rooms 5: 5.6.4
SecretRooms Hooks 1.12.2-1.0.0

Thaumcraft 6.1.BETA26 (pretty sure not the cause here)

**Comment by tterrag1098** [comment]
Both of these sound like mod issues, considering particles and rendering works just fine normally. I'm happy to help those devs figure out the issues, but you should report them to those devs.

**Comment by DoomRater** [comment]
I can report stuff over to Secret Rooms, but I guess I'll have to live with missing texture particles on Thaumcraft stuff as I don't think anyone's maintaining that build right now.  I also never got around to testing with the mining drill but once I do, if there are any issues I'll let them know as well.
