### ISSUE TITLE
Update to CTM MC1.12.2-1.0.0.26

### ISSUE THREAD

**Issue by LukyKrob** [Chisel-Team/ConnectedTexturesMod#109]
I updated the mod to the latest version and Chisel started crashing the game. Upon reverting to CTM - MC1.12.2-0.3.3.22, the modpack is turned on correctly.
[crash-2019-10-14_11.01.42-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/3723723/crash-2019-10-14_11.01.42-client.txt)

**Comment by ChloeDawn** [comment]
Chisel needs to update as the current release is using a deprecated API that was removed in the new CTM version. You will either need to remove Chisel or keep CTM downgraded until it is updated.

**Comment by tterrag1098** [comment]
Forgot just how old the last chisel update was. Hotfix should be up shortly.
