### ISSUE TITLE
[1.12] CTM causes a crash in Steve's Carts

### ISSUE THREAD

**Issue by 016Nojr** [Chisel-Team/ConnectedTexturesMod#11]
When I load up a modpack containing CTM, RebornCore and Steve's Carts, CTM causes a crash in Steve's Carts. I sent a message to @modmuss50 about it and he was pretty sure he knew what was going on (If the 1.12 version is supposed to be for 1.12, and not mismarked as 1.12 and supposed to be for 1.11.2). 

Mod Versions:

* Forge 14.21.0.2373 (Latest)
* CTM 1.11.2-0.1.1.6 (Latest) (I noticed the 1.11.2 in the version number, but it's marked as 1.12 on Curse)
* RebornCore 1.12-3.1.0.55 (Latest)
* Steve's Carts Reborn 1.12-2.4.2.20 (Latest)

**Comment by tterrag1098** [comment]
Where's the crash log?

**Comment by modmuss50** [comment]
Here: https://pastebin.com/1EAuBf0s I have a feeling (Please prove me wrong) its something to do with your code mod (not being updated to the latest forge?)

**Comment by 016Nojr** [comment]
This (https://pastebin.com/gc53WyJF) crash log is from the pack with only SC2, RC and CTM. The one modmuss sent is from the pack where I discovered the bug.
