### ISSUE TITLE
ModelCTM.retexture() fails to check if key is present in textures map

### ISSUE THREAD

**Issue by asiekierka** [Chisel-Team/ConnectedTexturesMod#110]
https://github.com/Chisel-Team/ConnectedTexturesMod/blob/1.12/dev/src/main/java/team/chisel/ctm/client/model/ModelCTM.java#L274

Should probably use getOrDefault, or do a containsKey beforehand.

**Comment by ChloeDawn** [comment]
The requested value is null-checked, I don't see a problem. What issues are you experiencing with regard to this design?

**Comment by ChloeDawn** [comment]
Nvm, I see this check was added after the fact. This ticket needs closing.
