### ISSUE TITLE
Textures not connecting with resource pack

### ISSUE THREAD

**Issue by robjw95** [Chisel-Team/ConnectedTexturesMod#111]
Since the new update the connected textures from soartex modded no longer connect

![ctm issue](https://user-images.githubusercontent.com/29755733/67143018-fbe7bb80-f234-11e9-8af1-a61847947faa.png)
![ctm before update](https://user-images.githubusercontent.com/29755733/67143022-06a25080-f235-11e9-820d-bacf05ad3a9f.png)

The above tiles are cobblestone dent, stone big tile, and stone sunken.

**Comment by tterrag1098** [comment]
The resource pack needs to be updated to include the .mcmeta files for the textures it's overriding, Minecraft won't load .mcmeta files from other resource packs (in this case Chisel's).
