### ISSUE TITLE
Error with Thermal mod

### ISSUE THREAD

**Issue by Fabiok89** [Chisel-Team/ConnectedTexturesMod#112]
Hi I'm trying to install the 4 packages of Thermal Thermal asks me to install other packages in order to start the game including one of these is the CTM. I'm using version 1.12.2 and all the mods are updated for this version. can anyone tell me how I can solve this problem so I can use these mods? I attach error message

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.2.389.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 11/1/19 11:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2085685248 bytes (1989 MB) / 2550136832 bytes (2432 MB) up to 3489660928 bytes (3328 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx3320M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version           | Source                                           | Signature                                |
	|:----- |:-------------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft                  | 1.12.2            | minecraft.jar                                    | None                                     |
	| LCH   | mcp                        | 9.42              | minecraft.jar                                    | None                                     |
	| LCH   | FML                        | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                    | None                                     |
	| LCH   | forge                      | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                    | None                                     |
	| LCH   | bspkrscore                 | 7.6.0.1           | [1.12]bspkrsCore-universal-7.6.0.1.jar           | None                                     |
	| LCH   | treecapitator              | 1.43.0            | [1.12]TreeCapitator-client-1.43.0.jar            | None                                     |
	| LCH   | actuallyadditions          | 1.12.2-r150       | ActuallyAdditions-1.12.2-r150.jar                | None                                     |
	| LCH   | ctm                        | MC1.12.2-1.0.0.29 | CTM-MC1.12.2-1.0.0.29.jar                        | None                                     |
	| LCH   | appliedenergistics2        | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar             | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | bdlib                      | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2.jar                     | None                                     |
	| LCH   | buildcraftlib              | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                     | None                                     |
	| LCH   | buildcraftcore             | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                     | None                                     |
	| LCH   | buildcraftbuilders         | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                     | None                                     |
	| LCH   | buildcrafttransport        | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                     | None                                     |
	| LCH   | buildcraftsilicon          | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                     | None                                     |
	| LCH   | buildcraftcompat           | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                     | None                                     |
	| LCH   | buildcraftenergy           | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                     | None                                     |
	| LCH   | buildcraftfactory          | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                     | None                                     |
	| LCH   | buildcraftrobotics         | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                     | None                                     |
	| LCH   | jei                        | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                        | None                                     |
	| LCH   | chisel                     | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar                     | None                                     |
	| LCE   | codechickenlib             | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux               | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                   | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar           | None                                     |
	| LC    | cofhworld                  | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | waila                      | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LC    | journeymap                 | 1.12.2-5.5.5b7    | JourneyMap-Mod-1.12.2-Unlimited.jar              | None                                     |
	| LC    | mantle                     | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LC    | mekanism                   | 1.12.2-9.8.2.389  | Mekanism-1.12.2-9.8.2.389.jar                    | None                                     |
	| LC    | pressure                   | 1.3.1.6           | pressure-1.3.1.6-mc1.12.1.jar                    | None                                     |
	| LC    | projecte                   | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                      | None                                     |
	| LC    | tconstruct                 | 1.12.2-2.12.0.157 | TConstruct-1.12.2-2.12.0.157.jar                 | None                                     |
	| LC    | thermalfoundation          | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion           | 5.5.4             | ThermalExpansion-1.12.2-5.5.4.43-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalcultivation         | 0.3.3             | ThermalCultivation-1.12.2-0.3.3.12-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermaldynamics            | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalinnovation          | 0.3.3             | ThermalInnovation-1.12.2-0.3.3.12-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | tlauncher_custom_cape_skin | 1.4               | tlskincape_1.12.2-1.4.jar                        | None                                     |
	| LC    | wailaharvestability        | 1.1.12            | WailaHarvestability-mc1.12-1.1.12.jar            | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.2.389.jar)
  mekanism.coremod.KeybindingMigrationHelper
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 440.97' Renderer: 'GeForce GT 710/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (34) from ActuallyAdditions-1.12.2-r150.jar
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-7.jar
		* buildcraftapi_blocks (1.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_boards (2.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_core (2.2) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_crops (1.1) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_enums (1.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_events (2.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_facades (1.1) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_filler (5.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_fuels (2.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_gates (4.1) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_items (1.1) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_library (2.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_lists (1.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_power (1.3) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_recipes (3.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_robotics (3.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_statements (1.1) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_tiles (1.2) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_tools (1.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_transport (5.0) from buildcraft-all-7.99.24.3.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-1.0.1.44.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-1.0.1.44.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.3.27-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-1.0.0.29.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-1.0.0.29.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-1.0.0.29.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-1.0.0.29.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-1.0.0.29.jar
		* journeymap|client-api (1.4) from JourneyMap-Mod-1.12.2-Unlimited.jar
		* journeymap|client-api-display (1.4) from JourneyMap-Mod-1.12.2-Unlimited.jar
		* journeymap|client-api-event (1.4) from JourneyMap-Mod-1.12.2-Unlimited.jar
		* journeymap|client-api-model (1.4) from JourneyMap-Mod-1.12.2-Unlimited.jar
		* journeymap|client-api-util (1.4) from JourneyMap-Mod-1.12.2-Unlimited.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.291.jar
		* MekanismAPI|core (9.8.1) from Mekanism-1.12.2-9.8.2.389.jar
		* MekanismAPI|energy (9.8.1) from Mekanism-1.12.2-9.8.2.389.jar
		* MekanismAPI|gas (9.8.1) from Mekanism-1.12.2-9.8.2.389.jar
		* MekanismAPI|infuse (9.8.1) from Mekanism-1.12.2-9.8.2.389.jar
		* MekanismAPI|laser (9.8.1) from Mekanism-1.12.2-9.8.2.389.jar
		* MekanismAPI|transmitter (9.8.1) from Mekanism-1.12.2-9.8.2.389.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.8.2.389.jar
		* pressureAPI (1.3.1.6) from pressure-1.3.1.6-mc1.12.1.jar
		* projecteapi (1.12.2-1.2.0) from ProjectE-1.12.2-PE1.4.1.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar`

**Comment by tterrag1098** [comment]
Looks like CodeChickenLib is throwing an error reading its config file. Not anything to do with CTM, and Thermal does not require CTM that I know of.
