### ISSUE TITLE
New version causes issues with Dynamic Trees

### ISSUE THREAD

**Issue by Gar0npeX** [Chisel-Team/ConnectedTexturesMod#116]
It seems that CTM 1.0.1.30 causes an issue with Dynamic Trees (Last updated in Nov 4)

https://pastebin.com/kC5psHJP

Using CTM 1.0.1.29 doesn't have any issues.

**Comment by tterrag1098** [comment]
They are trying to add to the list returned from getQuads. Good thing I made it immutable or it would have silently trashed my caches. Not a ctm issue.

**Comment by ghost** [comment]
Yep.  You're right.  I mistakenly assumed it returned a copy of the list.  Thanks.
