### ISSUE TITLE
CTM 1.0.1.30 crashes Dynamic Trees on startup

### ISSUE THREAD

**Issue by CalaMariGold** [Chisel-Team/ConnectedTexturesMod#118]
Pinpointed the cause to be from updating .29 to .30 

https://paste.dimdev.org/ahejayuxaj.mccrash

**Comment by coconuq** [comment]
Also met with this problem. CTM-MC1.12.2-1.0.1.30 conflicts if installed at the same time with Better With Mods and Dynamic Trees (separately, everything is fine) . CTM-MC1.12.2-1.0.1.29 installation solves the problem.

https://paste.dimdev.org/safudovuno.mccrash

**Comment by tterrag1098** [comment]
Duplicates #116
