### ISSUE TITLE
collides with storagedrawer mod in 1.12_2379

### ISSUE THREAD

**Issue by JasonKillsUs** [Chisel-Team/ConnectedTexturesMod#12]
i got this strange crash after adding CTM-MC1.11.2-0.1.1.6 to my mods:

"https://pastebin.com/QFHnLfaT" 

dunno who to tar and feather ;)

**Comment by tterrag1098** [comment]
Could you first try updating forge? You are pretty out of date.

**Comment by tterrag1098** [comment]
Scratch that, this is the same bug as #11, except forge is AGAIN swallowing the exception. Getting tired of this... 

Either way, fixed version is here: https://minecraft.curseforge.com/projects/ctm/files/2442600
