### ISSUE TITLE
[Documentation] Document the "texture" JSON entry

### ISSUE THREAD

**Issue by nihiltres** [Chisel-Team/ConnectedTexturesMod#121]
A while back, I requested a feature (through Discord), and it was implemented: CTM metadata in models supports a "`texture`" keyword that allows replacing just the "base" texture of a CTM map (the "default" non-CTM one) with one specified in the CTM metadata when CTM is present/active, without replacing the texture *entirely* as it would with the "`proxy`" keyword. The "`texture`" keyword is implemented in [ModelCTM.java](https://github.com/Chisel-Team/ConnectedTexturesMod/blob/1.12/dev/src/main/java/team/chisel/ctm/client/model/ModelCTM.java).

This feature is not currently documented, i.e. [in the wiki](https://github.com/Chisel-Team/ConnectedTexturesMod/wiki/CTM-Overrides-in-Models). It should probably be documented so that people who aren't me can easily learn about and use it. :)

Otherwise, thanks for implementing this feature: I'm using it in a mod I'm developing so that a pillar-like block can have a texture without an "end" border when CTM isn't present, but will use a fancier connected-style border when it is. :)

**Comment by tterrag1098** [comment]
Fixed https://github.com/Chisel-Team/ConnectedTexturesMod/wiki/CTM-Overrides-in-Models/_compare/600f4eb6c76bee0a6d65e4a87e8333bd5f7e7a34...2dc0a5f04a0f4553a2823de3d712244f64855702
