### ISSUE TITLE
Not Compatable at all

### ISSUE THREAD

**Issue by WolfHowlsAtLuna** [Chisel-Team/ConnectedTexturesMod#122]
So nothing is working I have version 1.12.2 and I got chisels and the CTM for 1.12.2 but it keeps saying its all wrong and wont let me play, if I was able to play the textures weren't loaded in still. basically the CTM wont work for me at all.

I'm not sure if its in the wrong folder or something but they are both in Mods.
That and I thought it was supposed to work for the version I have but I guess not

![Screenshot (1)](https://user-images.githubusercontent.com/60831873/81245369-c9d85400-8fe2-11ea-9777-10f9eb0c4879.png)

**Comment by tterrag1098** [comment]
The error is pretty clear that you need to update forge.

**Comment by WolfHowlsAtLuna** [comment]
Ah well mk my computer is so broken it doesnt update anythings so ill be ok
without it thx anyway
