### ISSUE TITLE
[Error] "FML has found a non-mod file CTM-MC1.12.2...."

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Chisel-Team/ConnectedTexturesMod#123]
Forge Version: forge-1.12.2-14.23.5.2847
CMT Version: CTM-MC1.12.2-1.0.2.31
latest.log: https://gist.github.com/pinkpig3777/64316ba184ae0b8236e86313e8de6db6
debug.log: https://gist.github.com/pinkpig3777/c5e6cbc9a2f087bc89bf7d6f2f4cfde0

Console error on startup:
[Server thread/INFO] [FML]: FML has found a non-mod file CTM-MC1.12.2-1.0.2.31.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.

Please fix. Thanks!

**Comment by tterrag1098** [comment]
This is a non-issue.
