### ISSUE TITLE
[1.12] CTMH Non-Functional and CTM Override Broken

### ISSUE THREAD

**Issue by ChloeDawn** [Chisel-Team/ConnectedTexturesMod#13]
The title pretty much sums this issue up.
CTMH functionality is broken in the CTM lib.
CTM overrides break the ~~universe~~ UV mapping.

**Mod version:** [0.0.1.2](https://minecraft.curseforge.com/projects/ctm/files/2442600)
**Forge version:** [1.12-14.21.1.2387](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2387/forge-1.12-14.21.1.2387-changelog.txt)
**Example resource pack:** [example.zip](https://github.com/Chisel-Team/ConnectedTexturesMod/files/1120684/example.zip)
###### EDIT: To prevent crash, remove CTMH override.

**Previous discussion:**
```
tterrag - Today at 10:18 PM
oh right
._.
ok so I think CTMH was poorly transferred to the new system

InsomniaKitten - Today at 10:19 PM
rip

tterrag - Today at 10:19 PM
since it used to be used for all 6 sides
it required two textures
one for top/bottom, and then the CTM map for the sides
obviously that's not necessary anymore
in fact, your RP crashes me on 1.10

InsomniaKitten - Today at 10:19 PM
ouch

tterrag - Today at 10:20 PM
not sure why it doesn't on 1.12
because CTMH says it requires two sprites
and you are not providing two
```

**Comment by tterrag1098** [comment]
Fixed via c79a48d1dbd8fecbc6540864f7b60c004daeeef4, a99b7a105679da490f54d74eaeef5fb1214e2475, and 1fbff9329e54ec97f886482dba69b5b85ceab216
