### ISSUE TITLE
[1.16] Model with no AO and no shade and texture with light 15 is still shaded on the item model

### ISSUE THREAD

**Issue by ChloeDawn** [Chisel-Team/ConnectedTexturesMod#132]
**Mod version:** [MC1.16.1-1.1.0.1](https://www.curseforge.com/minecraft/mc-mods/ctm/files/2988953)

![image](https://user-images.githubusercontent.com/9869940/88464239-01072480-ceb1-11ea-8666-3bee0968fc62.png)

The item still has light value, however

![image](https://user-images.githubusercontent.com/9869940/88464683-a7085e00-ceb4-11ea-9c82-6923c6711afe.png)

**Comment by tterrag1098** [comment]
Fixing this is not currently in the scope of CTM, the GL state when drawing items is fixed and lighting cannot be disabled per-element. It would have to be a (significantly invasive) forge patch.
