### ISSUE TITLE
[1.16] Model override's defined block render layer is not respected

### ISSUE THREAD

**Issue by ChloeDawn** [Chisel-Team/ConnectedTexturesMod#135]
**Mod version:** [MC1.16.1-1.1.0.1](https://www.curseforge.com/minecraft/mc-mods/ctm/files/2988953)
**Block models:** https://git.io/JJ4wI

Attempting to add a translucent overlay through model overrides to redstone ore results in the overlay being rendered on the block's default solid layer. There are no messages or errors regarding this in the log.

![image](https://user-images.githubusercontent.com/9869940/88464827-bd62e980-ceb5-11ea-816f-d0bb04efeec9.png)

**Comment by tterrag1098** [comment]
Fixed via bcb22985114cbbed513201b95df30a1a87a0bde6
