### ISSUE TITLE
Grass/Dirt Connected Texture.. Nonexistant [CTM - MC1.11.2-0.2.0.8]

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/ConnectedTexturesMod#14]
After entering a test world on a modpack I am developing, I have noticed that a specific arrangement of connected textures for grass/dirt blocks makes the texture invisible and gives me a noclip-esque view through the world. Below link is a screenshot of said issue as well as a google drive link to a folder containing all the logs:

[What It Looks Like](https://cdn.discordapp.com/attachments/333792855934107661/335019267210608640/unknown.png)

[All The Logs I Could Gather](https://drive.google.com/open?id=0B7ydOFE1sCthNnNpY1dxRzl1Zm8)

**Comment by tterrag1098** [comment]
It looks like you have Optifine and some other render mods installed, please reproduce without.

**Comment by ghost** [comment]
Oh, apologies for the time-waste then. I'm hoping there is a way to disable CTM's effect on all blocks except Chisel blocks, yet keep it so I can keep Chisel in the modpack but I'm not even sure that's possible. Would be a much simpler solution though.. I can do without CTM grass.

**Comment by ghost** [comment]
Nevermind I believe I found this myself in the configs :)

**EDIT**

Seems that'll disable CTM for chisel too.. I wish there was some sort of filter you could set on blocks.
