### ISSUE TITLE
[1.16.1] Failed Startup with Forge 32.0.107/8 due to changes with ModelRegistryEvent

### ISSUE THREAD

**Issue by SnowShock35** [Chisel-Team/ConnectedTexturesMod#140]
Hi Chisel Team,

Quick bug report regarding the 1.16.1 version of CTM with the two latest builds of Forge (32.0.107/8). Here are the details:

### Setup

- Minecraft 1.16.1
- Forge 32.0.107 (and build 108)
- CTM 1.1.0.1

### Description

The game fails to make it past the loading screen and Forge presents the user with an error message (see attached). According to the log file, this is because CTM is attempting to register model loaders after models have already started loading and that ModelRegistryEvent should be used to register loaders.

#### Screenshots

![Screenshot of Minecraft loading screen error with Forge 32.0.107/8 installed along with CTM mod version 1.1.0.1](https://user-images.githubusercontent.com/8388680/89889306-4b82e380-dbc9-11ea-969e-782d66b97fff.png)

#### Logs

- [latest.log](https://pastebin.com/j4BFGjzG)

#### References

The Forge changelog from <https://files.minecraftforge.net>.

> Build: 1.16.1-32.0.108 - Sun Aug 09 20:05:01 GMT 2020
> 	David Quintana:
> 		Fix ModelRegistryEvent firing every time resources reload instead of just once.
> 
> =========
> Build: 1.16.1-32.0.107 - Sat Aug 08 01:00:42 GMT 2020
> 	David Quintana:
> 		Move ModelRegistryEvent invocation to when the model loading is about to start.
> 		Freeze the ModelLoaderRegistry right after this event happens, just before model loading actually begins.
> 		This means ModelRegistryEvent is now the correct place to register loaders, as it was intended.
> 		This is a slight breaking change, but any mod that used FMLClientSetupEvent before will need to be updated regardless due to the existing race condition.

**Comment by ChloeDawn** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/commit/0bb3620a5285e2b607f51054744511faef9ec455
