### ISSUE TITLE
Invisible Draconic Evolution Items

### ISSUE THREAD

**Issue by SmortyMC** [Chisel-Team/ConnectedTexturesMod#144]
* Minecraft version: 1.12.2
* Mod version: CTM-1.0.2.31
* Minecraft Forge version: 14.23.5.2854
* Mods: (Draconic Evolution / Better With Mods / ConnectedTexturesMod)

The following items have a rendering issue making them invisible in hand and creative menu: Reactor Energy Injector, Reactor Stabilizer and Draconic Reactor Core. However, their block versions are still rendered correctly.

Removing either BetterWithMods or ConnectedTexturesMod fixes the problem, the problem only occurs with both installed and I already tweaked the config by disabling: Draconic Evolution shader options and BetterWithMods stumps and stratas CTM support options.

[latest.log](https://github.com/brandon3055/Draconic-Evolution/files/5512290/latest.log)

**Comment by DoomRater** [comment]
I have a similar issue involving Thaumic Augmentation 2.0.9 and CTM 1.0.2.31.  Running these two mods together alongside Twilight Forest 3.11 results in the Fiery Armor set not rendering in item form.  Removal of either mod fixes.  Downgrading Thaumic Augmentation to 1.1.19 also fixes.  I have no idea why.

My Forge is also 14.23.5.2854.  I've also let the Thaumic Augmentation authors know as much as I can.

**Comment by DoomRater** [comment]
https://github.com/TheCodex6824/ThaumicAugmentation/issues/124
Pretty sure this is on CTM's side, based on the description from TheCodex6824.

**Comment by tterrag1098** [comment]
Fixed in other project.
