### ISSUE TITLE
[1.15] Eldritch render type does not work with fullbright

### ISSUE THREAD

**Issue by tlitookilakin** [Chisel-Team/ConnectedTexturesMod#145]
Example:
`{
	"ctm": {
		"ctm_version": 1,
		"extra":{
			"light":15
		},
		"type": "eldritch"
	}
}`
Applying this to an mcmeta file renders with the texture warping of eldritch, but does not appear any brighter in dark places. Fullbright on non-eldritch render works as expected.

**Comment by tterrag1098** [comment]
Thanks, good catch, there were a couple methods that didn't copy the lighting data.
