### ISSUE TITLE
[1.12.2] Vissual glitch with AE2 smart cable

### ISSUE THREAD

**Issue by juraj-hrivnak** [Chisel-Team/ConnectedTexturesMod#150]
CTM - MC1.12.2-1.0.2.31
appliedenergistics2-rv6-stable-7

![2021-01-31_13 21 46](https://user-images.githubusercontent.com/71150936/106386734-bf62b380-63d6-11eb-9532-d38d5c325108.png)
`I don't know why.`

**Comment by tterrag1098** [comment]
This mod doesn't interfere with AE2's rendering in any way, I doubt this is a CTM bug.
