### ISSUE TITLE
1.12.2 - Mod conflict - Crash on launch

### ISSUE THREAD

**Issue by KreloX** [Chisel-Team/ConnectedTexturesMod#156]
Hello,
I was recently writing a compat mod for Twilight Forest and Spartan weaponry but when i installed CTM, because of twilight's dependency, it crashed with this log. It is very possible that the fault is on my side, because i'm fairly new to modding, but the crashlog mentioned your mod and even after some changes in my code it didn't work.
[crash-2021-06-27_11.14.18-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/6721342/crash-2021-06-27_11.14.18-client.txt)

**Comment by Tamaized** [comment]
Just to note, despite what Curseforge says, all dependencies for Twilight Forest are completely optional.

**Comment by KreloX** [comment]
Without CTM I get this:
[crash-2021-06-27_13.40.41-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/6721512/crash-2021-06-27_13.40.41-client.txt)

**Comment by Tamaized** [comment]
Wait... `forge-1.12.2-14.23.5.2855_mapped_snapshot_20171003-1.12-recomp.jar`
This is in a dev instance?
You have to use the appropriate deobfuscation parameters in your buildscript
