### ISSUE TITLE
Release for 1.17

### ISSUE THREAD

**Issue by Minionguyjpro** [Chisel-Team/ConnectedTexturesMod#157]
Make release for 1.17.

**Comment by Minionguyjpro** [comment]
???

**Comment by Minionguyjpro** [comment]
Why is this closed?

**Comment by swagbutt** [comment]
this was probably closed because they barely just for a alpha version for 1.16.5 out and probably wanna make that stable before going to 1.17. it will come out when it comes out

**Comment by Tamaized** [comment]
Forge isn't even out for 1.17, regardless this isn't an "issue" I'm not sure what you expect to gain for posting this. It's just you being demanding.

**Comment by Minionguyjpro** [comment]
I didnt know this mod was for Forge.

**Comment by swagbutt** [comment]
chisel has always been a forge mod

**Comment by Minionguyjpro** [comment]
Theres no place where stand it was Forge.
