### ISSUE TITLE
Mod for Fabric

### ISSUE THREAD

**Issue by Minionguyjpro** [Chisel-Team/ConnectedTexturesMod#158]
Please make this mod for Fabric like we can use it also with the Fabric mod loader.

**Comment by Tamaized** [comment]
Bruh just stop

**Comment by Minionguyjpro** [comment]
Why

**Comment by swagbutt** [comment]
for one this is not an issue and will probably be disregarded

**Comment by Minionguyjpro** [comment]
I think later Forge changes to Fabric maybe because its faster.

**Comment by Minionguyjpro** [comment]
Well, where should you post Suggestions then?

**Comment by swagbutt** [comment]
yes that would be the place to post this

**Comment by Minionguyjpro** [comment]
Here?

**Comment by Tamaized** [comment]
Demanding ports for different MC versions and/or loaders are not suggestions.

A proper suggestion would be about the mod content itself.

**Comment by Minionguyjpro** [comment]
Oh OK

**Comment by Minionguyjpro** [comment]
But why not Fabric?

**Comment by swagbutt** [comment]
maybe because the mod dev doesnt wanna make a fabric version who knows.

**Comment by Minionguyjpro** [comment]
And why should he not because i uses Fabric and i like it more then Forge because its faster.

**Comment by Tamaized** [comment]
Entitlement in a nutshell

**Comment by Minionguyjpro** [comment]
???

**Comment by swagbutt** [comment]
its probably the fact that very few people actually use fabric right now 99% of modded players use forge cause thats what 99% of the mods out right now use. im sure eventually mod devs will switch to fabric but that wont be anytime soon

**Comment by Minionguyjpro** [comment]
Speedrunners not

**Comment by Minionguyjpro** [comment]
I know a lot of youtubers which uses Fabric.

**Comment by tterrag1098** [comment]
Christ, it's already on fabric. This really wasn't necessary.
