### ISSUE TITLE
Add information for which mod loader in README.md file and Curseforge.

### ISSUE THREAD

**Issue by Minionguyjpro** [Chisel-Team/ConnectedTexturesMod#159]
Add information for which mod loader in README.md file and Curseforge so new people who uses the mod knows for which mod loader this is. I posted this because nowhere stand that this mod is Forge and with this people directly know this mod is for Forge.

**Comment by Tamaized** [comment]
![Screenshot_20210628-094406](https://user-images.githubusercontent.com/9671313/123646720-76802100-d7f5-11eb-84d6-776f12c8840f.png)

**Comment by Minionguyjpro** [comment]
??? where stand that?

**Comment by Minionguyjpro** [comment]
oh

**Comment by Minionguyjpro** [comment]
but not everyone watches the files tab

**Comment by Tamaized** [comment]
That's a *You* problem

**Comment by Minionguyjpro** [comment]
???

**Comment by Minionguyjpro** [comment]
Im really sure everyone just download it here:
![image](https://user-images.githubusercontent.com/66115754/123647363-4dc54f00-d828-11eb-9bc8-e0a377a43849.png)
