### ISSUE TITLE
CTM Model variants for adjacent blocks

### ISSUE THREAD

**Issue by CyanideX** [Chisel-Team/ConnectedTexturesMod#16]
It would be nice to have the ability to specify when a texture variant is used by defining adjacent block textures.

A particular situation in which this would be useful would be sand next to water. The sand could have a CTM variant with a light to dark gradient to look like a damp shoreline/coast.

**Comment by Drullkus** [comment]
Currently in CTM there exists an option to ignore blockstates within same block group. This is nice, but some blocks in Chisel span across multiple blocks. It would be better if there were a way to specify specific block states or even whole block groups. Such as `twilightforest:twilight_log#axis=x,variant=mangrove` or the whole group by simply `twilightforest:twilight_log`
