### ISSUE TITLE
Issue with Agricraft & Twilight forest 1.16.5

### ISSUE THREAD

**Issue by SGZ-Creations** [Chisel-Team/ConnectedTexturesMod#163]
https://github.com/AgriCraft/AgriCraft/issues/1396 possible to fix this issue here ?

**Comment by InfinityRaider** [comment]
Has been fixed on agricraft side, wait for the release. In the meantime there is a workaround mentioned on the Agricraft issue tracker.

**Comment by SGZ-Creations** [comment]
Ty
