### ISSUE TITLE
Crash on opening/loading modpack

### ISSUE THREAD

**Issue by SGZ-Creations** [Chisel-Team/ConnectedTexturesMod#166]
[crash-2021-10-21_11.44.31-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/7388017/crash-2021-10-21_11.44.31-client.txt)

**Comment by tterrag1098** [comment]
Superseded by #176

**Comment by SGZ-Creations** [comment]
This fixed now since u closed case?
