### ISSUE TITLE
CTM Biome Dependent.

### ISSUE THREAD

**Issue by DnatorGames** [Chisel-Team/ConnectedTexturesMod#17]
It would be awesome if there was an option for textures to recognize one biome from another. 

Such as adding seashells to sand while on beaches, and skulls to sand in the desert. :)

**Comment by Drullkus** [comment]
Duplicate of #1. 

Yes, this'd be interesting to have! I'm thinking this should be implemented on the model end, to avoid getting messy with the Rendertype system.
