### ISSUE TITLE
[1.18.2] Crash when starting the game

### ISSUE THREAD

**Issue by rabrunos** [Chisel-Team/ConnectedTexturesMod#177]
The game doesn't start with the mod, it just opens and closes.

Specifications:
- Minecraft: 1.18.2
- Forge: 40.0.12
- Launcher: MultiMC 0.6.14
- 8GB of RAM allocated for the game
- No mods installed, just CTM

## Log file
latest.log
https://mclo.gs/MsjQMux

debug.log
https://mclo.gs/Hv26rxK

**Comment by Daihok41** [comment]
Im no pro but could be cause its not updated to 1.18.2 yet lol

**Comment by tterrag1098** [comment]
Update
