### ISSUE TITLE
Chisel/ctm 1.10.2 0.2.1.20 all chisel blocks lost textures

### ISSUE THREAD

**Issue by pabthelamb** [Chisel-Team/ConnectedTexturesMod#18]
when we updated ctm to 0.2.1.20 I loaded my world and all chisel blocks turned into the purple/black missing textures thing. downgrading fixed it

**Comment by AlexPlus117** [comment]
Yep, it's happening to me too, but not only chisel blocks... even some other mods' blocks don't load.

**Comment by zISKo666** [comment]
same issue here with version 1.12-0.2.1.4
downgrading to 1.12-0.2.0.3 worked

**Comment by VladimirMangos** [comment]
Same for me. Also after update mod i see lot black planes over world graphical artefacts. All fixed after switch to prev. version. Possible related optifine compatibility with new mod version. But not check without optifine before switch back. [added] As note in next comment for me proble showup at 1.11.2

**Comment by kwpugh** [comment]
I get the same thing on the latest 1.11.2 version.
