### ISSUE TITLE
Inconsistence with ZYCraft blocks 1.18.2

### ISSUE THREAD

**Issue by PloJ94** [Chisel-Team/ConnectedTexturesMod#183]
I've opened an issue on this on the ZYCraft Github, but realized this might be CTM's issue instead, so I'm opening it here as well.

All info found here: https://github.com/nikita488/ZYCraft/issues/21#issue-1247857980

**Comment by tterrag1098** [comment]
This is a bug in Rubidium (or other similar mod(s)), not CTM.
