### ISSUE TITLE
[1.18.2] Connected Textures Don't Work

### ISSUE THREAD

**Issue by Flexico** [Chisel-Team/ConnectedTexturesMod#187]
I've tried both vanilla textures and Lithos texturepack, and the glass textures do not connect! They do work with Optifine though, so do I need to re-format the texture files?

**Comment by Flexico** [comment]
![2022-07-25_06 12 28](https://user-images.githubusercontent.com/5751770/180773042-6264e905-4b59-4e76-b554-5b6db4ccde47.png)

**Comment by tterrag1098** [comment]
You need a resource pack that uses CTM's format, such as https://www.curseforge.com/minecraft/texture-packs/mc-connected-ctm
