### ISSUE TITLE
No connected Textures? MC 1.16.5

### ISSUE THREAD

**Issue by jo-link-100** [Chisel-Team/ConnectedTexturesMod#189]
I am playing on Minecraft 1.16.5, and i love the Chisel Mod since i played it in the 1.12.2. But now in the Modpack (ATM6 To the Sky)        i played on the 1.16.5 there are no connected textures anymore. Is there a way to enable the connected Texture?

**Comment by tterrag1098** [comment]
Add a resourcepack with them such as https://www.curseforge.com/minecraft/texture-packs/mc-connected-ctm

**Comment by jo-link-100** [comment]
Hey why did you closed this as completed? My problem is not solved. I have installed the ressourcepack, but i still dont have any connected textures. Is there something i can do now?
