### ISSUE TITLE
AL Lib Crash

### ISSUE THREAD

**Issue by ViperKelly** [Chisel-Team/ConnectedTexturesMod#190]
Was directed here from the ATM help discord. I'm experiencing crashes that give a AL Lib cleanup report and the Minecraft crash log says Rendering Overlay as the Description.
![image_2022-08-26_003859135](https://user-images.githubusercontent.com/49590726/186849164-74de808b-10d7-406a-8ccd-4b63b5b65ac4.png)
[crash-2022-08-25_23.59.19-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/9430824/crash-2022-08-25_23.59.19-client.txt)

**Comment by tterrag1098** [comment]
See #192
