### ISSUE TITLE
i need 1.17

### ISSUE THREAD

**Issue by eltrevii** [Chisel-Team/ConnectedTexturesMod#191]

**Comment by TonimatasDEV** [comment]
Because you need it I don't think 1.17 will come out, better update your version of forge. All mods have been updated

**Comment by eltrevii** [comment]
@TonimatasMCDEV the mods i have need 1.17

**Comment by TonimatasDEV** [comment]
> Pass me the list of mods

**Comment by eltrevii** [comment]
@TonimatasMCDEV no need to, i only need that mod for 1.17

**Comment by TonimatasDEV** [comment]
> @TonimatasMCDEV no need to, i only need that mod for 1.17
Okey

**Comment by TonimatasMCDEV** [comment]
@Aritz331 
I did a small update that adds compatibility with 1.17
[https://github.com/TonimatasMCDEV/ConnectedTexturesMod-1.17/releases/tag/c8f093c](https://github.com/TonimatasMCDEV/ConnectedTexturesMod-1.17/releases/tag/c8f093c)

**Comment by TonimatasDEV** [comment]
> @TonimatasMCDEV no need to, i only need that mod for 1.17
@Aritz331 
I did a small update that adds compatibility with 1.17
https://github.com/TonimatasMCDEV/ConnectedTexturesMod-1.17/releases/tag/c8f093c

**Comment by eltrevii** [comment]
@TonimatasMCDEV sorry but i use 1.19 now
