### ISSUE TITLE
New Update (1.1.6) making the game crash in 1.18.2

### ISSUE THREAD

**Issue by Stupidplays** [Chisel-Team/ConnectedTexturesMod#200]
[crash-2023-02-03_20.22.23-fml.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/10579622/crash-2023-02-03_20.22.23-fml.txt)

**Comment by brisingraerowing** [comment]
It looks like the file is supposed to be for 1.19.2 and the 1.18.2 tag is incorrect. Downgrade to the previous release.

**Comment by FoxMcloud5655** [comment]
That is correct and can confirm that it was designed for 1.19.2, not 1.18.2.
