### ISSUE TITLE
CTM Connection issues

### ISSUE THREAD

**Issue by nikita488** [Chisel-Team/ConnectedTexturesMod#22]
**Mod version:** 0.2.1.5
**Forge version:** 1.12-14.21.1.2443

I have a problem. I have a block with subblocks that have **COLOR** property in it and it's seems that CTM not working properly for my blocks that have subblocks. All blocks trying to connect each other (it's trying to connect to blocks that have different meta). 
![2017-08-03_15 03 58](https://user-images.githubusercontent.com/6237881/28923350-659ff1c8-7866-11e7-9834-42eebb9d7274.png)
![2017-08-03_15 03 49](https://user-images.githubusercontent.com/6237881/28923361-6b43aebc-7866-11e7-89a2-ac45ba92b11d.png)
I think i know why this happens:
My block needs only one texture (it's not dependent on **COLOR** property) so i do this:
**ModelLoader.setCustomStateMapper(my_block, new StateMap.Builder().ignore(COLOR).build())** => this bind my block to "**normal**" location and now i can bind my texture to "**normal**" location.
But **COLOR** property used in few things: in **IBlockColor** (to switch color based on **COLOR** property), in **damageDropped** method, in **getStateFromMeta** and **getMetaFromState**. So when i remove **setCustomStateMapper** thing, it works fine:
![2017-08-03_15 55 12](https://user-images.githubusercontent.com/6237881/28923439-c2ac3c64-7866-11e7-9947-4ad7f0478be4.png)

**Comment by tterrag1098** [comment]
Add `"ignore_states": true` inside the `extra` tag

**Comment by nikita488** [comment]
Well, now it's just connects 
![2017-08-04_10 58 34](https://user-images.githubusercontent.com/6237881/28959646-01ce96ce-7904-11e7-8f99-77b77ebd0985.png)
But i need this:
![2017-08-03_15 55 12](https://user-images.githubusercontent.com/6237881/28959714-51063fbc-7904-11e7-9a51-4b8fe7784207.png)

**Comment by Drullkus** [comment]
Hmmm... Then you'll need to manually tell it the conditions. See here for how: https://github.com/Chisel-Team/ConnectedTexturesMod/wiki/Extra-Data#conditional-connections

**Comment by tterrag1098** [comment]
Issue persists, yet to investigate what is conflicting with custom statemappers. Could you post your model JSON?

**Comment by nikita488** [comment]
Model JSON: https://gist.github.com/nikita488/85c1d5e8afef006dd8440368d2a1307e
Blockstate JSON: https://gist.github.com/nikita488/26d7d7c5cbdc3e1b731302afb80376ad

**Comment by Drullkus** [comment]
Hmmm ctm metadata too?

**Comment by nikita488** [comment]
{
	"ctm": {
		"ctm_version": 1,
		"type": "ctm",
		"layer": "CUTOUT",
		"textures": [
		    "testmod:blocks/test_block_ctm"
		]
	}
}

**Comment by nikita488** [comment]
https://gist.github.com/nikita488/08c578891fa05bece2f3e55037781b81

**Comment by tterrag1098** [comment]
Fixed via cf4d97ab49b102f1be7e2b733b5ef472e334fd93
