### ISSUE TITLE
Modded glass block edges visible through self

### ISSUE THREAD

**Issue by blockninja124** [Chisel-Team/ConnectedTexturesMod#222]
While trying to add connected glass textures to create: new age I came onto this problem. You can see the edges through the glass
![image](https://github.com/Chisel-Team/ConnectedTexturesMod/assets/64211894/09e026f9-e130-4d23-8c42-8e07ce8c2e94)
My texture file:
![image](https://github.com/Chisel-Team/ConnectedTexturesMod/assets/64211894/9d35e45a-9db7-41ff-9262-71dea2c852d1)
My .png.mcmeta:
{
    "ctm":{
        "ctm_version": 1,
        "type":"CTM",
        "layer":"CUTOUT",
        "textures":[
            "create_new_age:block/reactor/glass-ctm"
        ]
    }
}
I thought maybe it was the wrong rendering type, but it seems to work with the example pack that has the same `CUTOUT` render type for its glass and it doesn't occur:
![image](https://github.com/Chisel-Team/ConnectedTexturesMod/assets/64211894/5084ec9a-3715-4225-8b29-dee9677ef4e2)
with a texture file I pretty much drew over:
![image](https://github.com/Chisel-Team/ConnectedTexturesMod/assets/64211894/17f23b75-718c-4120-81c2-d0e04bab5ccb)

I may have set something up wrong, but if not this may be an issue affecting modded glass? I'm not really sure what would cause this except for the render type being wrong. (I tried all the other render types as well, and they didn't fix the problem)

**Comment by brickyboy09** [comment]
Actually I think this is Create: new ages fault. I think they haven't set up their glass so that you can't see itself through itself, unlike vanilla glass.

**Comment by blockninja124** [comment]
Actually I think this is Create: new ages fault. I think they haven't set up their glass so that you can't see itself through itself, unlike vanilla glass.
