### ISSUE TITLE
[1.21][Neoforge] Neoforge 21.0.82 changes crash on launch

### ISSUE THREAD

**Issue by ffuentesm** [Chisel-Team/ConnectedTexturesMod#235]
https://pastebin.com/Krbji737
CTM-1.21-1.2.0
[23:32:00] [modloading-worker-0/ERROR] [ne.ne.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: ctm, class team.chisel.ctm.CTM
java.lang.NoSuchMethodError: 'void net.neoforged.fml.config.ModConfig.<init>(net.neoforged.fml.config.ModConfig$Type, net.neoforged.fml.config.IConfigSpec, net.neoforged.fml.ModContainer, java.lang.String)'
![image](https://github.com/user-attachments/assets/1730b4f3-e824-4dda-bef1-202bbdb89028)

**Comment by Periam** [comment]
Was to solve? I did not get a newer version of the mod and it is still crashing.

**Comment by PokeMaserJ** [comment]
> Was to solve? I did not get a newer version of the mod and it is still crashing.

So you don't have a new version of the mod ? Then go figure it's still crashing. You need to wait for an update

**Comment by Drullkus** [comment]
There is a mod update. Please update both CTM & NeoForge itself.

**Comment by Periam** [comment]
Thanks the latest version of the mod works fine with Neo 113, but it breaks 4 others mods..

**Comment by Drullkus** [comment]
Posting a crash log will help clarify the sources for your crashes

**Comment by Periam** [comment]
I do not thinks it is CTM, but if you want to check here are the logs and capture
Previous to the latest run Building Gadgets also crashed now I can not made it crash.

![image](https://github.com/user-attachments/assets/eea7da42-6386-4433-a9ba-2c03e9025953)

[crash-2024-07-20_15.53.53-fml.txt](https://github.com/user-attachments/files/16322058/crash-2024-07-20_15.53.53-fml.txt)
[debug.log](https://github.com/user-attachments/files/16322059/debug.log)
[latest.log](https://github.com/user-attachments/files/16322060/latest.log)

**Comment by Drullkus** [comment]
The issue has been identified in Modern Industrialization and a fix is currently in testing. Update to fix your issue from [MI on Curseforge](https://www.curseforge.com/minecraft/mc-mods/modern-industrialization/files/5549658), or from [Modrinth](https://modrinth.com/mod/modern-industrialization/version/2.2.10-beta)
