### ISSUE TITLE
Unnecessary cast to IdentityHashMap (instead of Map) causing crash

### ISSUE THREAD

**Issue by asiekierka** [Chisel-Team/ConnectedTexturesMod#24]
http://paste.asie.pl/pUoa

**Comment by Fundryi** [comment]
Was going to report the same :)
https://gist.github.com/Fundryi/5655218bfe7715106d46134df1c32dc9

**Comment by tterrag1098** [comment]
1.12 forge changed some internals that I unfortunately have to rely on. Fixed via ac486f77639592bad953bc49ce1d19dbccee4657

**Comment by Fundryi** [comment]
When will u push out the update?

**Comment by asiekierka** [comment]
Wasn't it already?

**Comment by Fundryi** [comment]
Its weird the new Twitch is so buggy, I can add Chisel but not CTM, I always have to download it manually on the website. Thanks for the info @asiekierka
