### ISSUE TITLE
Please mark your mod as 1.21.1 compatible.

### ISSUE THREAD

**Issue by JohnGoten** [Chisel-Team/ConnectedTexturesMod#244]
As Minecraft's update 1.21.1 is both considered LTS and only resolves a critical issue, it is important for mod developers to also properly tag their modifications to accommodate for this change.
The last thing users want is to be forced to manually browse CurseForge or Modrinth in the hopes to find a 1.21 not .1 mod in spite of (near) all being functional using a NeoForge 1.21.1 instance running the Prism Launcher or other alternatives.

It is so simple yet goes such a long way.

~ John

**Comment by Drullkus** [comment]
Added, though it seems it'll take a bit of time to update on CF 👍
