### ISSUE TITLE
Crash with refined storage

### ISSUE THREAD

**Issue by AndreiTS** [Chisel-Team/ConnectedTexturesMod#25]
[1.10.2]
ctm : 0.2.2.23
refined storage: 1.2.26
It happens when I open the craft grid, it works fine with ctm 0.2.1.21

crash: https://pastebin.com/VVUcYYJG

**Comment by AndreiTS** [comment]
crashed with multiverse pouch: https://pastebin.com/Tj8YQN0f

**Comment by sandalle** [comment]
Also happens with MC 1.11.2, Forge 1.11.2-13.20.1.2454, CTM MC1.11.2-0.2.2.11, Refined Storage 1.4.20. Only the client crashes when opening the Crafting Grid, the server remains running.

Crash-report: [crash-2017-08-16_10.45.34-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/1229068/crash-2017-08-16_10.45.34-client.txt)

Similar crash when looking (didn't try opening) a GraveStone Mod gravestone of another player (didn't try looking at my own gravestone).

crash-report: [crash-2017-08-16_10.54.57-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/1229082/crash-2017-08-16_10.54.57-client.txt)

Downgrading to CTM MC1.11.2-0.2.1.10 (and downgrading Chisel from MC1.11.2-0.0.13.23 to MC1.11.2-0.0.13.22 as MC1.11.2-0.0.13.23 is not compatible with CTM 0.2.1) fixes the crashes.

**Comment by tterrag1098** [comment]
Fixed via 07385ef48ce3b74d54a80a01230739354e4ad5ae

**Comment by sandalle** [comment]
Thank you for the quick fix. :) I was going to ask about 1.11 as well as the commit above was just for 1.10, but I found https://github.com/Chisel-Team/ConnectedTexturesMod/commit/40e3daf515acdf7cb843be55b216ff5d9be4636b after looking around first. ;)

**Comment by sandalle** [comment]
Upgraded to CTM MC1.11.2-0.2.2.12 (and Chisel MC1.11.2-0.0.13.23) and all looks good, thank  you for the quick release!
