### ISSUE TITLE
1.12 Ticking Player Crash

### ISSUE THREAD

**Issue by kwstoudt** [Chisel-Team/ConnectedTexturesMod#27]
Hello,
  Firstly, I am posting this here because the crash report I got says to contact the coremod authors first. Also, I am not sure that this mod has anything to do with the crash, but better safe than sorry. That said, here is what happened:

Leading up to the crash, I am trying to place maps inside of Bibliocraft Map Frames. However, it seems as though just holding the map can cause the crash. My crash report can be found [here.](https://pastebin.com/Pnfpw884)

I will also be posting this with the authors of the other coremods I have installed just in case.

**Comment by tterrag1098** [comment]
This has nothing to do with CTM.

In the future, just try removing those mods and reproducing the crash, there's nothing in this log that points to us.
