### ISSUE TITLE
[1.10.2] Crash when looking up recipe of Blood Altar in JEI

### ISSUE THREAD

**Issue by 3TUSK** [Chisel-Team/ConnectedTexturesMod#28]
One of my friend encountered a weird crash, as title said, when looking up the recipe of Blood Altar (from Blood Magic) in JEI. Because stacktrace points to CTM, I decide to report it here first. 

Crash report: https://pastebin.com/0Ldhgqnt

**Comment by tterrag1098** [comment]
You're out of date
