### ISSUE TITLE
Enhanced IFacade interface

### ISSUE THREAD

**Issue by CreativeMD** [Chisel-Team/ConnectedTexturesMod#29]
Hey,

It's been a while since i asked the last time and just want to know if there are any news about the enhancement of the IFacade interface mentioned here: https://github.com/Chisel-Team/Chisel/pull/414#issuecomment-297497157

**Comment by tterrag1098** [comment]
Sorry for the massive delay, it kept getting caught up in other things. Finally ported the changes over. This may not release for a bit, since it is a major API break, I need to let people prepare by adding a max CTM version in their dependencies.

**Comment by CreativeMD** [comment]
Awesome!!! I will try it out soon. Thank you very much.

**Comment by CreativeMD** [comment]
When will this be merged into the 1.11.2 and 1.12.2 branch?
