### ISSUE TITLE
[1.10.2] Crash with PlusTiC on startup

### ISSUE THREAD

**Issue by SanAndreaP** [Chisel-Team/ConnectedTexturesMod#3]
MC: 1.10.2
Forge: 12.18.3.2281
Chisel: 0.11.23
CTM: 0.1.0.8
PlusTiC: 5.0.1.4

When starting the game, it crashes with the following exception:
https://gist.github.com/SanAndreasP/f8b49c4f121657f632e372b46dd5de17#file-latest-log-L1905
(here is another issue, from PlusTiC https://github.com/Landmaster/PlusTiC/issues/51)

This doesn't seem to be an issue with PlusTiC, as it runs fine on its own (w/ all the other mods I have, just w/o CTM). Downgrading Chisel and deactivating CTM fixes the issue.

**Comment by Landmaster** [comment]
@SanAndreasP This seems to be an EnderIO/Chisel API issue.

**Comment by tterrag1098** [comment]
Yes, see Chisel-Team/Chisel#449
