### ISSUE TITLE
Glass pane texture broken on North and West facing sides.

### ISSUE THREAD

**Issue by laserlemons** [Chisel-Team/ConnectedTexturesMod#30]
I don't know whether or not this is the resource pack's fault or the mod's fault so I'm reporting it to both.

Version CTM - MC1.12-0.2.2.7 using version 1.2 of the resource pack.

The North and West facing side of glass panes are backwards where they connect to blocks. There are also solid lines on the top on bottom of the panes, too, which makes them look not-so-borderless

![2017-09-18_18 41 49](https://user-images.githubusercontent.com/6501298/30572288-84e4fc7c-9ca1-11e7-9c9e-fa4914454da1.png)

**Comment by tterrag1098** [comment]
Yeah this is known. The vanilla model uses different UVs on those sides so we need to tweak it.

**Comment by laserlemons** [comment]
Is this a problem with the pack or the mod? I'd like to try to fix it for myself if it's just the pack.

**Comment by tterrag1098** [comment]
It can be fixed in the pack, the vanilla pane model is just incompatible with CTM and needs to be remade custom.

**Comment by Dimentive** [comment]
I’m having the same issue.

![Glass](https://user-images.githubusercontent.com/34230933/54936316-89bf2a80-4f22-11e9-9ba6-072fd99abaa3.png)

**Minecraft version:** 1.12.2
**Forge version:** 14.23.5.2781
**Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version 1.62)
**ConnectedTexturesMod version:** 0.3.3.22 (latest)

**Comment by tterrag1098** [comment]
That's great but it's still an issue with CTP, not this project.

**Comment by Dimentive** [comment]
Oh, my apologies. Somebody gave me the link to this issue, and I thought I was on the ConnectedTexturesMod issue tracker.

By the way, I experience the issue even without the Connected Textures Pack.
