### ISSUE TITLE
CTM on Model Inheritance not working

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/ConnectedTexturesMod#33]
<img width="540" alt="screen shot 2017-10-10 at 7 35 37 pm" src="https://user-images.githubusercontent.com/5010174/31419721-3d84dd5e-adf2-11e7-836b-cad93baad674.png">

Spec: https://cdn.discordapp.com/attachments/176563404218171392/363819038935220234/model_inheritance_2.zip

**Comment by P3rf3ctXZer0** [comment]
![2018-01-18 12_09_02-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/35113970-178f9cf8-fc38-11e7-91bb-f30cd1fae725.png)

**Comment by tterrag1098** [comment]
Fixed via b2cb2fdab5de850d5edfb6a394cb755c535f4b94
