### ISSUE TITLE
CTM 0.2.3.9+Draconic Evolution 2.3.4.265

### ISSUE THREAD

**Issue by tgstyle** [Chisel-Team/ConnectedTexturesMod#34]
The Energy Crystals are invisible with CTM installed. (hand, inventory, JEI or creative menu)

**Comment by tterrag1098** [comment]
Please check your log for errors, JEI usually only hides items if they crash during rendering.

**Comment by brandon3055** [comment]
Do the crystals render outside of JEI? So in the creative menu or in your inventory?

**Comment by tgstyle** [comment]
They do not render in hand, inventory, JEI or creative menu.

**Comment by tgstyle** [comment]
The only error on loading that I can see in the log for JEI is from Chisel, and should not have anything to do with it.

[main/ERROR] [jei/jei]: Failed to register mod plugin: class team.chisel.common.integration.jei.ChiselJEIPlugin
java.lang.IllegalArgumentException: Invalid ingredient found. Parameter Name: ingredient Class: class net.minecraft.item.ItemStack Object: 1xtile.air@0

**Comment by tgstyle** [comment]
CTM had no errors in the log, this is what I could see from DE. Nothing rendering related.
https://gist.github.com/tgstyle/c7e54fc3a48c61988228c557d4fd87e1

**Comment by brandon3055** [comment]
Hmm... try disabling shaders in DE's config.

**Comment by tgstyle** [comment]
Tried, noticed the change in world. They still do not render in hand, inventory, JEI or creative menu.

**Comment by covers1624** [comment]
I have a hard time believing that CTM is the problem here, unless it is somehow conflicting with CCL's IItemRenderer hook witch is highly unlikely, as i presume things like TD covers, EnderStorage's items, and other fancy DE blocks render fine. Can you post your entire log?

**Comment by tgstyle** [comment]
It is easily reproduced with just having only DE (and dependencies) and CTM installed. Without CTM installed DE renders them fine. I will post a log when I have more time.

Edit: Also note in world renders fine

**Comment by tgstyle** [comment]
OK so today I was getting ready to pull my hair out because I could not get it to reproduce. Then I remembered I had "The Official Connected Textures Pack" enabled in some cases. It turns out there is something in the resource pack conflicting, it just happened to be with CTM installed since it is the enabler for the pack.

**Comment by AcidKat** [comment]
I'm gonna go ahead and bump this, I have the same issue happening, only reproducible with CTM + a texture pack (Specifically Unity in my case), causes all power crystals to suddenly become invisible (Screenshot 2), and also this (see the glass pane on the right): 

Screenshot 1:
![2017-12-12_08 52 37](https://user-images.githubusercontent.com/15000462/33875634-bf28290c-df1a-11e7-9083-4712ecebcffe.png)

This weird texture stretching also happens with Binnies mods, seems to bug out bottles (fruit juices etc).

Screenshot 2:
![2017-12-12_08 52 44](https://user-images.githubusercontent.com/15000462/33875636-c0b9ffa2-df1a-11e7-92d9-32e41a17aad4.png)

All of these errors seem to go away as soon as no texture packs are loaded or when CTM is removed.

Further info:
**Forge**: 14.23.1.2562
**CTM**: 0.2.3.9

**Comment by ouroborus** [comment]
https://github.com/brandon3055/Draconic-Evolution/issues/958

**Comment by tterrag1098** [comment]
Does this still occur?

**Comment by tgstyle** [comment]
Not trying to revive just close this issue. Last I knew it was fixed.
