### ISSUE TITLE
CTM Face culling

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/ConnectedTexturesMod#35]
<img width="423" alt="screen shot 2017-10-28 at 8 08 40 pm" src="https://user-images.githubusercontent.com/5010174/32140351-ced5faf4-bc1b-11e7-8ef2-10b31b1d9218.png">

![2017-10-28_18 45 03](https://user-images.githubusercontent.com/5010174/32140357-d6724880-bc1b-11e7-8caf-7839b13c6baf.png)

CTM is being disabled on faces that WOULD be culled by the block's method but are actually not being culled as defined by the block's model json.

**Comment by P3rf3ctXZer0** [comment]
Yeah I can confirm this happening. I am glad someone else has reported it.

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/9

**Comment by P3rf3ctXZer0** [comment]
https://github.com/P3rf3ctXZer0/MC-1.12.2-TGGRS/issues/11

**Comment by tterrag1098** [comment]
I....don't think this still happens. But the report doesn't really give context (>.> @Drullkus )
