### ISSUE TITLE
 Tesselating block model

### ISSUE THREAD

**Issue by DoxDrac** [Chisel-Team/ConnectedTexturesMod#40]
First time user.. so sorry if its wrong.. but a user on my server was kicked and cant log on! Then i got close to his base and i got kicked!
And not neither of us can log in!

[crash-2017-12-30_18.32.54-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/1594615/crash-2017-12-30_18.32.54-client.txt)

**Comment by tterrag1098** [comment]
brandon3055/Draconic-Evolution#1002
