### ISSUE TITLE
Texture Type edges_full Has Missing Face Logic

### ISSUE THREAD

**Issue by ChloeDawn** [Chisel-Team/ConnectedTexturesMod#41]
North/south faces fail to do correct state checks for west diagonals.
This issue can be reproduced with obsidian and portal blocks using [CTP](https://minecraft.curseforge.com/projects/ctp).

**Mod version:** [MC1.12-0.2.3.12](https://minecraft.curseforge.com/projects/ctm/files/2519601)

**Screenshot of north/south facing portal:**

![screenshot_0](https://i.imgur.com/8TBAHL0.png)

**Screenshot of west/east facing portal next to previous portal:**

![screenshot_1](https://i.imgur.com/200aBJc.png)

**Recording of logic updates:**

![recording_0](https://thumbs.gfycat.com/RecklessCourageousAfricanharrierhawk-max-14mb.gif)

**Comment by tterrag1098** [comment]
Can no longer reproduce on 0.3.2.x

**Comment by CovertJaguar** [comment]
Running CTM 1.0.2.31 and can reproduce:

![2020-06-17_16 45 57](https://user-images.githubusercontent.com/1521970/84961803-115dff80-b0ba-11ea-9e33-90a1e9e61fba.png)

Mod List:
AIImprovements-1.12-0.0.1b3
AetherWorks-1.12.2-1.0.0.3
AppleCore-mc1.12.2-3.3.0
AppleSkin-mc1.12-1.0.9
Architect-MC1.12-1.2.0.6
AtlasExtras-1.12.2-1.8
AutoRegLib-1.3-32
Baubles-1.12-1.5.2
BetterFps-1.4.8
BetterStorageToo-1.12.2-3.0.0.2
BiblioCraft[v2.4.5][MC1.12.2]
Botania+r1.10-363
CTM-MC1.12.2-1.0.2.31
CalmDownZombieGuy-1.12.2-1.0.0
CarryOn+MC1.12.2+v1.12.3
Ceramics-1.12-1.3.7
Chameleon-1.12-4.1.3
Charm-1.12.2-1.3.7
ChunkAnimator-MC1.12-1.2
ClientTweaks_1.12.2-3.1.11
CookingForBlockheads_1.12.2-6.5.0
Customized-Dungeon-Loot-1.12+-(v.1.0.3)
Decocraft-2.6.3_1.12.2-modified
DynamicSurroundings-1.12.2-3.6.1.0
DynamicTrees-1.12.2-0.9.8
DynamicTreesPHC-1.12.2-1.4.2
DynamicTreesTC-1.12.2-1.4.1e
EmbersRekindled-1.13-hotfix2
EnchantmentDescriptions-1.12.2-1.1.20
FarmingForBlockheads_1.12.2-3.1.28
FastWorkbench-1.12.2-1.7.3
Flamingo-1.12-v1.11
Forgelin-1.8.4
HorsePower-1.12.2-2.6.4.74
HungerOverhaul-1.12.2-1.3.3.jenkins148
ImprovedBackpacks-1.12.2-1.5.0.0
Inspirations-1.12.2-0.2.9
JustEnoughResources-1.12.2-0.9.2.60
LagGoggles-1.12.2-5.8-132
LibraryEx-1.12.2-1.1.3
MagicBees-1.12.2-3.2.25
MagmaMonsters-0.3.0
Mantle-1.12-1.3.3.55
MathParser.org-mXparser-4.0.0
MmmMmmMmmMmm-1.12-1.14
MouseTweaks-2.10-mc1.12.2
Mystical+Mechanics-0.12
NetherEx-1.12.2-2.1.7
NetherPortalFix_1.12.1-5.3.17
OTG-Core
OpenTerrainGenerator-1.12.2+-+v8.3
OreLib-1.12.2-3.6.0.1
PTRLib-1.0.4
Pam's+HarvestCraft+1.12.2zg
Patchouli-1.0-20
Ping-1.12.2-1.4.5
Quark-r1.6-179
Reagenchant-1.12.2-1.1.1
Reliquary-1.12.2-1.3.4.796
Rex's-Additional-Structures-1.12.x-(v.2.3.1)
RoguelikeDungeonsFnarEdition-1.12.2-2.1.3
Roots-1.12.2-3.0.28
SereneSeasons-1.12.2-1.2.18-universal
Soot-1.6
SophisticatedWolves-1.12.2-3.13.8
SoundFilters-0.12_for_1.12
SpartanShields-1.12.2-1.5.4
SpartanWeaponry-1.12.2-beta-1.3.8
SpartanWeaponryArcana-1.12.2-beta-1.0.3
SpiceOfLife-mc1.12-1.3.12
StorageDrawers-1.12.2-5.4.2
StorageDrawersExtras-1.12-3.1.0
Tails-1.12-1.10.0
Thaumcraft-1.12.2-6.1.BETA26
ThaumicJEI-1.12.2-1.6.0-27
ThaumicTraveler'sDream-Compact-1.12.2-v1.2
TickCentral-2.6
ToolBelt-1.12.2-1.9.12
Trinkets+and+Baubles-0.30.1
UniDict-1.12.2-2.9.6
Waddles-1.12.2-0.6.0
WanionLib-1.12.2-2.4
Waystones_1.12.2-4.1.0
antiqueatlas-1.12.2-4.6.3
anvilpatch-1.0.0
astikorcarts-1.12.2-0.1.2.7
bettercaves-1.12.2-2.0.3
blockdrops-1.12.2-1.4.0
controllable-1.12.2-0.8.0
coroutil-1.12.1-1.2.37
dynamicTreesRoots-0.2.1
dynamictreesQuark-1.12.2-1.0.2
enchantingwiththaumcraft-1.2
environmentalcreepers-1.12.2-1.6.0
fairylights-2.1.10-1.12.2
foamfix-0.10.10-1.12.2
forestry_1.12.2-5.8.2.422
gravestone-1.10.3
iceandfire-1.9.1-1.12.2
incontrol-1.12-3.9.16
instantunify-1.12.2-1.1.2
jei_1.12.2-4.15.0.293
just-enough-harvestcraft-1.12.2-1.7.0
literalascension-1.12.2-2.0.0.0
llibrary-1.7.19-1.12.2
millenaire-8.1.0
minecolonies-1.12.2-0.11.841-ALPHA-universal
moresoundconfig-1.0.4
mystgears-1.1.4
mysticallib-1.12.2-1.7.0
mysticalworld-1.12.2-1.8.4
parry-1.0-hotfix
placeableitems-3.3
platforms-1.12.0-1.4.6
railcraft-12.0.0
ropebridge-1.12-2.0.7
savemystronghold-1.12.2-1.0.0
shetiphiancore-1.12.0-3.5.9
skylanterns-1.12.1-1.0.1
solcarrot-1.12.2-1.8.4
spartanfire-0.08
stg-1.12.2-1.2.3
thaumicperiphery-0.3.1
theoneprobe-1.12-1.4.28
topaddons-1.12.2-1.13.0
twilightforest-1.12.2-3.10.1013-universal
weather2-1.12.1-2.6.12
wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed
worldedit-forge-mc1.12.2-6.1.10-dist
worldutils-1.12.2-0.4.2
yoyos_1.12.2-1.3.3.25
