### ISSUE TITLE
Issue with AE2 Facades

### ISSUE THREAD

**Issue by anders0nmat** [Chisel-Team/ConnectedTexturesMod#42]
So there is an issue with the pattern type (i guess so, in chisel assets it's coded with "V").  This happens: 

![2018-02-13_17 28 16](https://user-images.githubusercontent.com/30215279/36161345-b4f30ea2-10e3-11e8-82ce-f898387dd92b.png)

Besides the light bugs, AE2 uses the full x32 image instead of a part of it.

**Comment by tterrag1098** [comment]
Nothing I can do about this, it's their render code...
