### ISSUE TITLE
"IllegalAccessError" apparently from CTM?

### ISSUE THREAD

**Issue by Gyromax** [Chisel-Team/ConnectedTexturesMod#47]
Minecraft-Version: 1.12.2
Forge-Version: 1.12.2-14.23.2.2628
CTM Ver: 1.12-0.2.3.12
Chisel Ver: 1.12.2-0.2.0.31

So i started today, upgrading my Server and Client to Minecraft 1.12.2.
After a whole lot of "damn, i forgot this Mod or that Corelib", i got the Server up and running. After that i copied the Mods to my Client, added a few "Client only Mods" and tried to start it. Always crashes on Start-Up with the following Sentence.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CTM (ctm)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.client.Minecraft.field_110452_an from class team.chisel.ctm.CTM

Not sure how to fix it, or why it comes to the Error, because the same Version is running just fine on the Server.

Here is the Crash-Log:
https://pastebin.com/CnKZ1WEc

If you need the "fml-latest-log" or any other Information, just tell me and i'll try to provide it as fast as i can.

**Comment by covers1624** [comment]
`CTM-MC1.12-0.2.3.12.zip` It appears CTM was downloaded as a zip file due to (i assume edge) being dumb. Rename the file from .zip to .jar and it should be fine.

**Comment by Gyromax** [comment]
It worked, thanks covers1624.
Just kinda confused that some mods have been downloaded as a .jar and some as a .zip with me using the same browser for everything. And as u guessed it was edge. (Having a fight with my Firefox atm).
Didn't change the Ending, cause i remembered something bout some Mods being delivered as a .zip in earlier MC-Versions (if my Memory is right).

**Comment by tterrag1098** [comment]
You're not wrong, but zip file mods have been deprecated for many years now. Mainly due to this reason, FML cannot read manifest data from a zip file (because they don't have one). Which is where our AT is stored, which is what fixes this problem.
