### ISSUE TITLE
CTM connect to blocks of a different type

### ISSUE THREAD

**Issue by actioninja** [Chisel-Team/ConnectedTexturesMod#48]
I'd like to be able to define other blocks that a CTM texture would connect to.  A bit like how edge currently works, but also allowing CTM by itself.

For an example of what I mean, this is how stained glass looks in a pack I work on with CTM:
![2018-03-22_14 14 32](https://user-images.githubusercontent.com/5194834/37799241-5e049a5a-2ddc-11e8-8460-70c3252f4bdc.png)

However, I would like to be able to remove the borders between each color of glass and keep the frame surrounding all of them.

For an example of what I mean, here's a quick bad edit whipped up in gimp:
![examplepic](https://user-images.githubusercontent.com/5194834/37804004-61b8c55a-2def-11e8-8361-3ac3bfeffca2.png)
So here, the blue, red, and green colored glasses would all be configured to connect to each other as though they were the same block, but still using their own CTM texture.

To make the syntax less horrible, there also could be some kind of macro function.  Like it connects with all blocks containing "glass," or "colored glass" instead of specifying each individual color of glass.

**Comment by ChloeDawn** [comment]
@actioninja https://github.com/Chisel-Team/ConnectedTexturesMod/wiki/Extra-Data#conditional-connections

**Comment by actioninja** [comment]
Nice, it already exists, good job me.
closing.
