### ISSUE TITLE
[Client Crash] Tesselating block model (a random cursed block)

### ISSUE THREAD

**Issue by Sewef** [Chisel-Team/ConnectedTexturesMod#51]
Hi there.
Me and a friend are playing on a server. He placed a block of Chiseled Stone (Poison Variant) from Chisel and it made us crash everytime we are loading this block.

Here the crash-log : https://pastebin.com/Wnsuxqfb

Here the block : 
https://i.imgur.com/46OFtR2.png
(I replaced him by a redstone_block using /setblock command from the console)

Placing a Chiseled Stone (Poison) again makes crash again.

Edit : Got another crash by placing another kind of chiseled stone. So the Chiseled Stone (Poison Variant) is not the problem, I guess.

I tried disabled CTM in the config file, but no change. (So mby it's a Chisel bug, idk)

**Comment by ChloeDawn** [comment]
What are those high-resolution lumps of red?

**Comment by Sewef** [comment]
They are Rhodochrosite from NuclearCraft, placed using DraconicEvolution's control "Place Item In World" :þ

Update: it looks like it's the Encased Bricks variant that makes crash. Placing some in the empty space next to the Redstone Block killed us again

**Comment by ChloeDawn** [comment]
does it still crash if you remove the rhodochrosite?

**Comment by Sewef** [comment]
...
I removed those things, placed the floor
I placed again the rhodothing at the bottom of the wall, and I crashed.

I don't get it. At least we have a clue.

**Comment by ChloeDawn** [comment]
I think CTM is trying to get information about the Draconic Evolution placed item, and DE is returning invalid information for some reason.

**Comment by tterrag1098** [comment]
DE bug, they return null from getBoundingBox which is invalid. This would crash in vanilla too...
