### ISSUE TITLE
1.12.2 Crash when placing Mekanism Induction Cell next to Thermal Dynamics fluxduct

### ISSUE THREAD

**Issue by xAlicatt** [Chisel-Team/ConnectedTexturesMod#52]
Not even sure if i'm reporting this in the right place since there are about 6 different mods mentioned in the crash report. But since it's a client-side crash (crash to desktop but fortunately comes with a crash report), I'm here thinking this is the most likely culprit.

https://gist.github.com/xAlicatt/38d711d349685ca4f021ac3f665d02de

**Comment by covers1624** [comment]
Update ThermalDynamics, a patch was released to fix this.
