### ISSUE TITLE
Using F3 + t to reload textures causes CTM to display missing texture

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/ConnectedTexturesMod#54]
CTM version: CTM-MC1.12-0.2.3.12
Forge: 1.12.2-14.23.2.2611

Fresh launch:
![2018-04-11_23 06 31](https://user-images.githubusercontent.com/13294361/38654452-6bae5612-3ddd-11e8-8f5e-3088cf0190c6.png)

After pressing F3 + t:
![2018-04-11_23 06 52](https://user-images.githubusercontent.com/13294361/38654467-7bb27106-3ddd-11e8-9565-0bdd522f96ea.png)

This is happening in the dev environment while I'm working on a mod that uses CTM.
mod: [Cathedral Mod](https://github.com/ferreusveritas/Cathedral)

file: [mcmeta file](https://github.com/ferreusveritas/Cathedral/blob/master/src/main/resources/assets/cathedral/textures/blocks/cathedral/glass_stained_firetaijitu.png.mcmeta)
The only way to get the texture to resolve is to close out completely and relaunch.  Although this is a work around I do a lot of block models and reload constantly using F3 + t to see my changes.  If the problem is on my end I would appreciate somebody setting me straight.

Thanks.

**Comment by Drullkus** [comment]
Those are some pretty sweet blocks! Unfortunately I’ll have to pass this issue to @tterrag1098 since he’s the engineer behind most of CTM. The mcmeta is syntactically correct though.

**Comment by ghost** [comment]
Thank you! :)

**Comment by ChloeDawn** [comment]
Yah, reloading textures in-game has been broken for a while. I think there was a change within Forge that broke it. It's affecting other mods that rely on resource reloads too such as JEI's item blacklist.

**Comment by tterrag1098** [comment]
Happy to report this is finally fixed, I will be pushing an update soon. The fix was pretty simple, but it remains a mystery why I was not seeing this on some of my own things. Either way, I tested with your mod (a great test case btw) and everything seems to work fine now.

**Comment by Nethet** [comment]
what was the cause of the bug ?

**Comment by ChloeDawn** [comment]
Texture metadata caches not being invalidated on reload. You can see it in the referenced commit.

**Comment by Tora-B** [comment]
In my case, I managed to narrow this down to LiteLoader as the cause. I can confirm that merging the current 1.10 and 1.12 branches fixed the problem, at least in my case. An official build would be nice though for others.
