### ISSUE TITLE
Wet sand texture missing.

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/ConnectedTexturesMod#61]
Sometimes the wet sand texture shows up as a missing texture. I'm sure it is caused by Optifine, but I don't know how to fix it. I've disabled connected textures on Optifine, yet the wet sand still sometimes shows up as missing texture.

**Comment by NyteLyte** [comment]
Is this fixable without removing optifine?

**Comment by NyteLyte** [comment]
Actually, every single connected texture does this, it's not only a problem with wet sand, glass has the missing texture texture on the overlap between two blocks

**Comment by LuigiHutch** [comment]
https://github.com/Chisel-Team/ConnectedTexturesPack/issues

**Comment by NyteLyte** [comment]
oh shit, i actually went to the wrong github page, im retarded sorry
