### ISSUE TITLE
Extreme Reactors Not displaying complete structure

### ISSUE THREAD

**Issue by xp0colipse** [Chisel-Team/ConnectedTexturesMod#65]
When this mod is installed, I build an extreme reactor and upon placing the last block to complete the reactor, it doesn't complete. No the game doesn't crash, but but the reactor can only be turned on indirectly with a program I run with Computercraft. If I build a reactor WITHOUT this mod installed it works as it should. If I build the reactor to completion, save and exit the game and re-enter, it somehow fixes it. I am waiting in anticipation hoping this bug can be fixed. If you need any info I will give whatever you need. Thanks and I hope to hear from someone with a fix!
![2018-06-30_15 29 36](https://user-images.githubusercontent.com/19493262/42128492-e9aa420c-7c7a-11e8-8287-bcda131b41c4.png)
![2018-06-30_15 29 40](https://user-images.githubusercontent.com/19493262/42128493-edcaae80-7c7a-11e8-9972-edcff209d49f.png)

**Comment by tterrag1098** [comment]
There's almost no way CTM could affect this...it is a clientside mod. Report this to Extreme Reactors.
