### ISSUE TITLE
Immersive engineering conflict on render

### ISSUE THREAD

**Issue by Kazzum** [Chisel-Team/ConnectedTexturesMod#67]
Hi, so I am playing my own custom modpack for awhile and hadn't been having any issue until I started using immersive engineering, once I opened the book and went to "Multiblock constructions" and tried to move to the Third page the game crashed. After some trouble shooting I found disabling CTM made Immersive engineering work correctly. I also tried just disabling chisel however the crash persisted. 

(I apologize if this issue already exists I did a cursory look and didn't find a match) 

[Crash 2(without Chisel).txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/2152933/Crash.2.without.Chisel.txt)
[Crash-1(with Chisel).txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/2152934/Crash-1.with.Chisel.txt)

**Comment by PanSzelescik** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63
