### ISSUE TITLE
CTM Rendering Item crash

### ISSUE THREAD

**Issue by Snekco** [Chisel-Team/ConnectedTexturesMod#68]
Hello,

I've been trying to get some mods to work together for my friends and I to play and in doing so I have run into this error consistently: **java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap cannot be cast to gnu.trove.map.hash.TIntObjectHashMap**

This only happens when I import CTM into my mod folder. The crash reports seems to say that it is having issues with something in codechicken.lib.

I have tried getting all of the thermal mods from team CoFH, as well as Thaumcraft to mesh together. When I select the item menu in creative mode to test the the items, I select any of the of the thermal tabs or Thaumcraft and I get the error above.  Attached is the full crash report. 

Any help with this would be much appreciated because I want to add twilight forest and chisel.

Thank you for your time
-Snek

[crash-2018-07-01_12.24.48-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/2153014/crash-2018-07-01_12.24.48-client.txt)

**Comment by PanSzelescik** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63
