### ISSUE TITLE
1.10: Connected Textures mod breaks Mekanism pipe rendering.

### ISSUE THREAD

**Issue by Dilnu** [Chisel-Team/ConnectedTexturesMod#7]
Hi, on 1.10 Connected Textures Mod breaks Mekanism pipes rendering.

Specifically the mekanism pipes are all invisible.
My minecraft version is 1.10.2
Forge: 12.18.3.2297
CTM-MC1.10.2-0.1.0.13
Mekanism: 9.2.2.301
MC Multipart: 1.4.0

**Comment by HenryLoenwind** [comment]
Probably the same cause as https://github.com/SleepyTrousers/EnderIO/issues/4261

**Comment by tterrag1098** [comment]
See Chisel-Team/Chisel#459
