### ISSUE TITLE
java.lang.NoClassDefFoundError - Fixed in 0.3.2.18

### ISSUE THREAD

**Issue by Partonetrain** [Chisel-Team/ConnectedTexturesMod#72]
https://pastebin.com/5qmP8dbx

version 0.3.2.17 crashes with CodeChickenLib when rendering a CTM block. This didn't happen with 0.3.1.16.

There is a config in CCL to not crash on this error (an instead render invisible block), so I wasn't really sure which one to report this to but I chose CTM because this only happened after updating CTM.

**Comment by TheRealDadbeard** [comment]
Same here. Crashing after update. Right after loading a chiseled block.

**Comment by tterrag1098** [comment]
Fixed in 0.3.2.35/0.3.2.18 ref 1277a566e41de29ef4f5faf0538d5831eae3aa5a
