### ISSUE TITLE
Crash with CTM

### ISSUE THREAD

**Issue by Diamssword** [Chisel-Team/ConnectedTexturesMod#75]
[crash-2018-07-29_19.22.21-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/2239017/crash-2018-07-29_19.22.21-client.txt)

This crash append when CTM mod is present in my pack, the crash append when I opened the creative inventory and switched to the moddeds tabs pages, strangely, no items render make me crash when looking through JEI.

Any idea of what could cause this?

**Comment by tterrag1098** [comment]
#72

**Comment by tterrag1098** [comment]
Sorry, #63
