### ISSUE TITLE
attempt to switch tab in creative closes game

### ISSUE THREAD

**Issue by KiraLinux** [Chisel-Team/ConnectedTexturesMod#76]
when I want to switch tabs in creativity mode, the game just closes

CTM-MC1.12-0.3.0.15
1.12.2-forge1.12.2-14.23.4.2718

https://pastebin.com/C8J1bNEr
https://pastebin.com/LHKWaEJ9

**Comment by covers1624** [comment]
You need to update CTM.

**Comment by KiraLinux** [comment]
OK

**Comment by tterrag1098** [comment]
#63
