### ISSUE TITLE
Startup Crash with latest Forge release for 1.12.2

### ISSUE THREAD

**Issue by duhnunes** [Chisel-Team/ConnectedTexturesMod#82]
Recently the forge version 14.23.5.2768 has become recommended and this mod is causing crash in the game after initialization.
Say LexMano in this session (3th comment)
http://www.minecraftforge.net/forum/topic/66711-forge-1122-142342768-startup-crash/

**Comment by ZombieHDGaming** [comment]
Please stop reporting this to ever single mod in your coremods list. If you looked at the log, you would clearly see that Better Foliage is the mod at fault here. Report it to them and/or remove the mod from your mod folder.

**Comment by duhnunes** [comment]
I'm just reporting the list that LexManos says
