### ISSUE TITLE
 Crash when looking at Endstone uses in JEI

### ISSUE THREAD

**Issue by hayesj1** [Chisel-Team/ConnectedTexturesMod#85]
Short description:
Game crashes when viewing uses of endstone in JEI.

Steps to reproduce the problem:
Press the hotkey to view of the uses of a block/item, while hovering over endstone.
...
Expected behaviour:
Recipes using endstone should have been displayed.

Downgrading to 0.3.2.20 fixed the crash for me.

Versions:
CTM: 0.3.3.22
Minecraft: 1.12.2
Forge: 1.12.2-14.23.5.2784

Log file:
Lastest Log (Too big for Pastebin):
https://www.dropbox.com/s/p0egxc3uqmd9xm7/latest.7z?dl=0

Crash:
https://pastebin.com/vqBWMh5Q

**Comment by tterrag1098** [comment]
`    at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.func_188616_a(DynamicItemAndBlockModel.java:48)
`

Report this to CyclopsCore
