### ISSUE TITLE
Crash on loading into a world with LLibrary 1.7.16

### ISSUE THREAD

**Issue by CammiePone** [Chisel-Team/ConnectedTexturesMod#86]
Crash Report: https://pastebin.com/TG1ei966
LLibrary Version: 1.7.16
Minecraft Forge Version: 14.23.5.2795

**Comment by tterrag1098** [comment]
Cool, so why report it here?

**Comment by tterrag1098** [comment]
https://github.com/iLexiconn/LLibrary/issues/105
https://github.com/iLexiconn/LLibrary/issues/107

Please do the slightest amount of research before blindly sending bugs to places they don't belong.

**Comment by CammiePone** [comment]
I... thought I sent it on the LLibrary Github. I have no idea what went wrong there, because I typed "llibrary github" into Google. Sorry about this.
