### ISSUE TITLE
Game not starting with version MC 1.12.2-0.3.3.22

### ISSUE THREAD

**Issue by SirAron111** [Chisel-Team/ConnectedTexturesMod#88]
Not really a crash but when updating to the newest version of the connected textures mod I press play on the curse/twitch launcher and then press play on the minecraft launcher normally this pops up the pack loading screens where the loading bars do the loading thing but that just doesn’t pop up just nothing happens all just vanishes.

**Comment by tterrag1098** [comment]
Please provide some sort of log or crash report, or there's nothing I can do.

**Comment by SirAron111** [comment]
That the thing it doesn’t crash it just vanishes on startup. I tried to force crash but that doesn’t work to it just vanishes. Maybe you can try it yourself just download the newest version of my pack "Dimension Zero" and then add the newest version of the texture mod (also update the forge to the version stated to be used by your change log) start it up and it vanishes. could it be some kind of conflict?

**Comment by Andromander** [comment]
There should at least be a startup log. I don't recall the name off the top of my head, but it should be `fml-startup-client` or similar.

**Comment by tterrag1098** [comment]
Configure the launcher you are using to not hide the console on game exit.

**Comment by SirAron111** [comment]
https://pastebin.com/gTUjfWbQ
This is all i could get
I hope that helps this damn not starting think only happens with ctm updated works fine if not updated to lates version

**Comment by Andromander** [comment]
Can you try disabling Optifine? I'm not 100% sure, but just to be certain that it may or may not be a cause.

**Comment by SirAron111** [comment]
Seems like it really was Optifine it started without it. Strange this only happened with your mod. I went through them all to test it. But it seems that the newest version of Optifine”OptiFine_1.12.2_HD_U_E3” Fixed the problem and they work fine together.
Thx for the help.
