### ISSUE TITLE
Emissive textures cannot have shaded sides

### ISSUE THREAD

**Issue by yrsegal** [Chisel-Team/ConnectedTexturesMod#90]
All shapes made with emissive textures appear flat. While this is often desirable, it can also make models look odd or improper. An example of this:

The desired behavior, with the coils appearing as 3d objects
<img width="587" alt="shaded sides" src="https://user-images.githubusercontent.com/6596492/50406880-b08e8900-079a-11e9-8e24-332275744138.png">

The current behavior, with the coils appearing as 2d objects
<img width="528" alt="flat color" src="https://user-images.githubusercontent.com/6596492/50406881-b08e8900-079a-11e9-82d2-b99d478650a0.png">

Implementing a way to allow emissive quads to have their shadedness controllable would be highly appreciated. (Especially since Vanilla already has such a configurable property.)

**Comment by yrsegal** [comment]
Re: what I said on discord:

The first effect was achieved by manually using textures with the shading color modifiers applied. It can also be achieved by using LibrarianLib glow to render the model, which [sets the *global* lightmap value used by the model render](https://github.com/TeamWizardry/LibrarianLib/blob/1.12/src/main/java/com/teamwizardry/librarianlib/features/utilities/client/GlUtils.kt#L21-L27), rather than setting all of the quads to the same value.

**Comment by tterrag1098** [comment]
This should be possible now with latest forge
