### ISSUE TITLE
Emissive textures will stop being emissive when many tintindices are involved.

### ISSUE THREAD

**Issue by yrsegal** [Chisel-Team/ConnectedTexturesMod#91]
I'm not sure exactly what's going on here, but this model has 7 tintindices, one for each face of the coils. The coils all use the same texture. If the colors provided for the tintindices are the same, the problem goes away.

The emissive quads retain the lack of shading, which means it isn't just a failure of the emissive detection entirely. Removing the one glowing piece will cause another to become the one glowing piece.
<img width="594" alt="what the hell" src="https://user-images.githubusercontent.com/6596492/50406954-13cceb00-079c-11e9-96c3-5555b8ab47fa.png">

What it looks like with a single tintindex for the coils, for reference.
<img width="528" alt="flat color" src="https://user-images.githubusercontent.com/6596492/50406881-b08e8900-079a-11e9-82d2-b99d478650a0.png">

**Comment by yrsegal** [comment]
Re: what I said on discord:

This is an item. If the 6 tintindices used for the glowing object are all set to the same color, emissive quads work as expected. If they're even one point of rgb off, it breaks.

**Comment by yrsegal** [comment]
![2018-12-29_15 18 44](https://user-images.githubusercontent.com/6596492/50541886-1bfe9f00-0b7d-11e9-9354-70bee6a9772c.png)

On the latest repository version of CTMLib. [The used resourcepack](https://github.com/Chisel-Team/ConnectedTexturesMod/files/2718757/ctmrp.zip) (with custom items created with a [quick and hacky edit to ctmlib](https://gist.github.com/yrsegal/38cf26ceae24f8f3964089b96325e531))

The "_same" blocks all have a tint of 0xFFFFFF for each face. The others have hue-based tints.

**Comment by tterrag1098** [comment]
Do you know if this still occurs on latest forge?

**Comment by tterrag1098** [comment]
I suspect it does not.
