### ISSUE TITLE
[COL] Crashes on Load w/ Forge 1.12.2-14.23.5.2807

### ISSUE THREAD

**Issue by Link5261** [Chisel-Team/ConnectedTexturesMod#94]
CTM ver: CTM-MC1.12-0.3.0.15.jar
  Mods involved: Included in this Feed The Beast mod pack
    (https://www.feed-the-beast.com/projects/ftb-horizons-iii/files/2575013). (117 total)

  Some friends in a Discord server set up a modded Minecraft server two days ago using the above-
linked mod pack and the server was able to run. I grabbed the same mods from that pack and dropped 
them in the mods folder for my Minecraft install directory. Attempting to load the game in this state 
through Forge leads to the affixed crash image and log.

  One thing I attempted to solve the issue was updating this and any other mod in the pack to
progressively-newer versions to fix crash on load and dependency errors, and I eventually constructed a 
stable build that can launch fine and play single player without issue. The reason I'm not satisfied with this 
conclusion though is that the server spits back error messages about expecting the lower version mods 
for the ones that I needed to update, so I'm in a sort of catch-22 situation where the files I need to join 
the server prevent me from loading the game, but the fix to that load issue I came up with isn't 
supported by the server.

![game_crash](https://user-images.githubusercontent.com/43685379/51070116-9b728080-1609-11e9-9ab4-30c9cacb1475.png)

[crash-2019-01-12_01.21.02-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/2751767/crash-2019-01-12_01.21.02-client.txt)

**Comment by Link5261** [comment]
Ended up needing to use an older Forge version and everything cleared up.

**Comment by tterrag1098** [comment]
No just update CTM as the very top issue explains

![image](https://i.imgur.com/jwvhUYc.png)
