### ISSUE TITLE
CTM connection overrides don't handle actual states

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/ConnectedTexturesMod#98]
Resourcepack: [connect_to_actualstate.zip](https://github.com/Chisel-Team/ConnectedTexturesMod/files/2977108/connect_to_actualstate.zip)

Resource pack is set up so that top textures of stone slabs will connect to Raw Granite blocks and Fences that has a North connection. It is expected that the tops will connect to both of these blocks. However, it only connects to the Granite and not the fence, despite it having a north connection.

![fence_is_north_but_slab_doesnt_connect](https://user-images.githubusercontent.com/5010174/54517847-0b5df980-4920-11e9-8dd7-c3a9797827a8.png)

**Comment by tterrag1098** [comment]
Fixed via https://github.com/Chisel-Team/ConnectedTexturesMod/commit/6bab85ef64b098b9ab854757c3b388f182f60e80

**Comment by FreneticScribbler** [comment]
This feature would be really useful to me - any chance you could release it (on 1.12)?
