### ISSUE TITLE
keeps crashing so uh....im just leaving this here for help

### ISSUE THREAD

**Issue by Millerrex** [Chisel-Team/ConnectedTexturesMod#99]
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 3/31/19 12:49 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.animania.common.handler.ItemHandler.regItemEggColors(ItemHandler.java:301)
	at com.animania.common.events.EntityEventHandler.onEntityJoinWorld(EntityEventHandler.java:81)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_85_EntityEventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72897_h(World.java:3546)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1820)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.animania.common.handler.ItemHandler.regItemEggColors(ItemHandler.java:301)
	at com.animania.common.events.EntityEventHandler.onEntityJoinWorld(EntityEventHandler.java:81)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_85_EntityEventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72897_h(World.java:3546)

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [EntityPlayerSP['Millerrex66'/415, l='MpServer', x=-161.50, y=86.00, z=239.50], EntityOtherPlayerMP['Anzu_Wylei'/352892, l='MpServer', x=-247.12, y=67.00, z=226.40], EntityOtherPlayerMP['Paxumo'/371795, l='MpServer', x=-240.65, y=68.00, z=226.53]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-163,69,240), Chunk: (at 13,4,0 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3526669 game time, 3651016 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 76 total; [MoCEntitySnail['Snail'/3203, l='MpServer', x=-108.98, y=73.00, z=244.39], EntityItem['item.item.exoticbirds.magpie_egg'/392192, l='MpServer', x=-134.07, y=72.00, z=199.67], EntitySheep['Sheep'/3205, l='MpServer', x=-92.71, y=64.00, z=267.51], MoCEntityHorse['WildHorse'/3085, l='MpServer', x=-163.16, y=51.00, z=229.09], EntityCustomNpc['Benjamin'/3086, l='MpServer', x=-167.50, y=70.00, z=238.50], EntityItem['item.item.arrow'/396436, l='MpServer', x=-206.32, y=27.00, z=190.86], EntityItem['item.item.bone'/396437, l='MpServer', x=-205.20, y=28.00, z=191.87], EntityOtherPlayerMP['Anzu_Wylei'/352892, l='MpServer', x=-247.12, y=67.00, z=226.40], EntityItem['item.item.exoticbirds.peafowl_egg'/399525, l='MpServer', x=-185.19, y=70.00, z=184.50], MoCEntityBee['Bee'/382625, l='MpServer', x=-117.32, y=67.00, z=205.90], EntityOtherPlayerMP['Paxumo'/371795, l='MpServer', x=-240.65, y=68.00, z=226.53], EntitySheep['Sheep'/3109, l='MpServer', x=-143.76, y=82.00, z=161.50], MoCEntityMaggot['Maggot'/382624, l='MpServer', x=-130.23, y=70.00, z=207.32], EntitySheep['Sheep'/3110, l='MpServer', x=-156.50, y=77.00, z=160.50], EntitySheep['Sheep'/3111, l='MpServer', x=-150.52, y=77.00, z=169.77], MoCEntityMaggot['Maggot'/382626, l='MpServer', x=-131.35, y=70.00, z=203.04], EntitySheep['Sheep'/3112, l='MpServer', x=-154.50, y=78.00, z=169.29], EntityAnimalTrader['Animal Trader'/3113, l='MpServer', x=-149.13, y=76.00, z=178.40], EntityPig['Pig'/3242, l='MpServer', x=-83.25, y=64.00, z=192.54], MoCEntityAnt['Ant'/3115, l='MpServer', x=-143.00, y=63.00, z=297.51], EntitySheep['Sheep'/3243, l='MpServer', x=-97.48, y=67.00, z=189.74], MoCEntityMaggot['Maggot'/2988, l='MpServer', x=-207.57, y=69.00, z=185.21], EntityPeafowl['Peafowl'/3116, l='MpServer', x=-161.03, y=68.00, z=293.88], EntityPig['Pig'/3244, l='MpServer', x=-87.25, y=67.00, z=194.50], MoCEntitySnail['Snail'/3247, l='MpServer', x=-87.50, y=73.00, z=237.81], EntityItem['item.item.exoticbirds.peafowl_egg'/396594, l='MpServer', x=-168.08, y=71.00, z=188.82], MoCEntityAnt['Ant'/3252, l='MpServer', x=-97.46, y=63.00, z=279.00], EntityPig['Pig'/3253, l='MpServer', x=-83.69, y=64.00, z=284.50], MoCEntityBass['Bass'/3255, l='MpServer', x=-85.66, y=62.00, z=305.70], EntityItem['item.item.exoticbirds.magpie_egg'/394430, l='MpServer', x=-126.27, y=70.00, z=217.41], MoCEntityAngler['Angler'/3256, l='MpServer', x=-87.61, y=62.00, z=301.85], MoCEntityGoldFish['GoldFish'/3257, l='MpServer', x=-84.85, y=62.14, z=292.15], MoCEntityManderin['Manderin'/3258, l='MpServer', x=-84.38, y=62.00, z=292.15], MoCEntityStingRay['StingRay'/3259, l='MpServer', x=-81.87, y=62.00, z=292.89], MoCEntityAngler['Angler'/3260, l='MpServer', x=-84.75, y=62.00, z=292.59], MoCEntityCaveOgre['CaveOgre'/403771, l='MpServer', x=-170.50, y=27.00, z=316.50], MoCEntityGoldFish['GoldFish'/3261, l='MpServer', x=-89.85, y=62.02, z=314.15], MoCEntityManderin['Manderin'/3262, l='MpServer', x=-87.85, y=62.00, z=301.16], MoCEntityStingRay['StingRay'/3263, l='MpServer', x=-84.00, y=62.00, z=305.19], EntitySkeleton['Skeleton'/408774, l='MpServer', x=-221.50, y=24.00, z=192.50], MoCEntityAnchovy['Anchovy'/3264, l='MpServer', x=-88.52, y=62.44, z=313.15], MoCEntityGoldFish['GoldFish'/3266, l='MpServer', x=-90.04, y=62.00, z=318.15], EntitySpider['Spider'/408773, l='MpServer', x=-219.50, y=24.00, z=188.50], EntityMagpie['Magpie'/3139, l='MpServer', x=-142.18, y=75.00, z=187.51], MoCEntitySnail['Snail'/3140, l='MpServer', x=-144.26, y=74.00, z=188.65], EntityItem['item.item.string'/396610, l='MpServer', x=-120.13, y=31.00, z=293.88], EntityCreeper['Creeper'/400067, l='MpServer', x=-220.50, y=17.00, z=166.50], EntityMagpie['Magpie'/3142, l='MpServer', x=-133.23, y=72.00, z=199.52], EntityMagpie['Magpie'/3144, l='MpServer', x=-126.51, y=70.00, z=217.78], EntityItem['item.item.crickets'/406351, l='MpServer', x=-199.43, y=70.00, z=241.25], EntityMagpie['Magpie'/3146, l='MpServer', x=-129.49, y=70.00, z=212.78], MoCEntitySnail['Snail'/3020, l='MpServer', x=-197.85, y=69.00, z=227.90], EntityItem['item.item.exoticbirds.magpie_egg'/394826, l='MpServer', x=-141.58, y=75.00, z=187.38], MoCEntitySnail['Snail'/3149, l='MpServer', x=-133.27, y=67.00, z=263.11], MoCEntityMole['Mole'/3151, l='MpServer', x=-136.17, y=64.00, z=290.97], MoCEntitySnail['Snail'/3162, l='MpServer', x=-123.28, y=74.00, z=178.72], EntityMagpie['Magpie'/3164, l='MpServer', x=-123.35, y=70.00, z=218.16], EntityZooKeeper['Zoo Keeper'/2917, l='MpServer', x=-217.53, y=68.00, z=219.74], EntityAnimalTrader['Animal Trader'/2918, l='MpServer', x=-246.22, y=65.07, z=227.78], EntityZooKeeper['Zoo Keeper'/3047, l='MpServer', x=-180.48, y=74.00, z=153.54], EntityItem['item.item.exoticbirds.magpie_egg'/395105, l='MpServer', x=-129.13, y=70.00, z=211.97], EntityPeafowl['Peafowl'/3048, l='MpServer', x=-185.14, y=70.00, z=184.95], EntityItem['item.item.exoticbirds.magpie_egg'/394351, l='MpServer', x=-104.26, y=70.00, z=219.18], EntityPeafowl['Peafowl'/3050, l='MpServer', x=-168.88, y=71.00, z=189.35], EntityCustomNpc['Noppes'/3051, l='MpServer', x=-179.50, y=70.00, z=242.50], EntityZooKeeper['Zoo Keeper'/3052, l='MpServer', x=-192.32, y=69.00, z=276.79], MoCEntityTiger['Tiger'/3053, l='MpServer', x=-145.98, y=63.00, z=318.03], MoCEntityRat['Rat'/408689, l='MpServer', x=-240.50, y=20.00, z=167.50], EntitySheep['Sheep'/3191, l='MpServer', x=-102.42, y=66.00, z=165.74], EntitySheep['Sheep'/3192, l='MpServer', x=-113.19, y=70.00, z=175.49], EntitySheep['Sheep'/3194, l='MpServer', x=-98.48, y=67.00, z=187.06], EntityPig['Pig'/3195, l='MpServer', x=-100.93, y=66.00, z=199.95], EntityMagpie['Magpie'/3196, l='MpServer', x=-104.20, y=70.00, z=218.49], EntityPig['Pig'/3197, l='MpServer', x=-110.77, y=73.00, z=230.71], EntityItem['item.item.crickets'/399864, l='MpServer', x=-213.42, y=69.00, z=253.29], MoCEntitySnail['Snail'/3199, l='MpServer', x=-112.82, y=73.00, z=232.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 543727296 bytes (518 MB) / 1610612736 bytes (1536 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2814 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                             | Signature                                |
	|:------ |:-------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2814.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2814      | forge-1.12.2-14.23.5.2814.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | craftstudioapi       | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | animania             | 1.6.2             | animania-1.12.2-1.6.2.jar                          | None                                     |
	| LCHIJA | backpack             | 3.0.2             | backpack-3.0.2-1.12.2.jar                          | None                                     |
	| LCHIJA | zawa                 | 1.12.2-1.5.5      | zawa+-+1.5.5+(1.12.2).jar                          | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCHIJA | bookworm             | 1.12.2-2.1.0      | bookworm+-+2.1.0+(1.12.2).jar                      | None                                     |
	| LCHIJA | cfm                  | 6.2.0             | cfm-6.2.0-mc1.12.2.jar                             | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
	| LCHIJA | chisel               | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| LCHIJA | craftablehorsearmour | 1.3               | CraftableHorseArmour-1.3.0-1.12.jar                | None                                     |
	| LCHIJA | customspawner        | 3.11.4            | CustomMobSpawner-3.11.4.jar                        | None                                     |
	| LCHIJA | customnpcs           | 1.12              | CustomNPCs_1.12.2(30Jan19).jar                     | None                                     |
	| LCHIJA | mocreatures          | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar                | None                                     |
	| LCHIJA | exoticbirds          | 1.0               | Exotic+Birds+1.12.2-2.2.1.jar                      | None                                     |
	| LCHIJA | llibrary             | 1.7.17            | llibrary-1.7.17-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil               | 8.0.0             | fossilsarcheology-8.0.0.jar                        | None                                     |
	| LCHIJA | jei                  | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LCHIJA | faunanatural         | 1.12.2-1.3.2      | NaturalFauna+Mod-1.12.2-1.3.2.jar                  | None                                     |
	| LCHIJA | wit                  | 1.0.25            | WIT-1.12-1.0.25-44.jar                             | None                                     |
	| LCHIJA | jurassicraft         | 2.1.21            | JurassiCraft-1.12.2-2.1.21.jar                     | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4836' Renderer: 'Intel(R) HD Graphics 630'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2814
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 630 GL version 4.5.0 - Build 22.20.16.4836, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz

**Comment by tterrag1098** [comment]
Animania issue, though it appears it's already fixed by them.
